### ISSUE TITLE
node 18+ still supported?

### ISSUE THREAD

**Issue by roughnecks** [cheeaun/phanpy#1008]
I just ran `npm install` on my production build.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lru-cache@11.0.2',
npm WARN EBADENGINE   required: { node: '20 || >=22' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
```

How comes?

**Comment by cheeaun** [comment]
@roughnecks you're right. Seems like upgrading to Lingui v5 has bump it to minimum Node.js v20 https://lingui.dev/releases/migration-5

I didn't notice this because I'm already running this on Node.js v20 locally. I'll need to update the docs.

Are you able to try running it on Node.js v20?

**Comment by roughnecks** [comment]
I prefer not to, so I just downloaded the tarball release and used that.. but I got another issue.

I can see the GIF button (had it enabled in the custom build) but if I search anything it says "no result found". I think the button shouldn't be there at all, right?

**Comment by roughnecks** [comment]
Nevermind, logged out/in and it fixed itself.
