### ISSUE TITLE
Put known languages into separate zone

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#101]
I write messages in 2 languages. It's hard to select them, because languages list is too big.

It would be great if known languages (languages with disabled translate functionality) will at the top of selector for easier access

**Comment by Alex0007** [comment]
I can confirm they are now located on the top of the list.

But it seems like android <select> aligning list items relatively to selected item. So now 2 known languages on the top, but list can be aligned to second element of the list (so you still need to scroll a little). Not a big issue though.

Thanks, @cheeaun!

**Comment by nhan000** [comment]
@Alex0007 does that require you to uncheck every language in this list except for the 2 languages you know? I thought the built-in translator should be used to also read languages you don't speak?

![image](https://user-images.githubusercontent.com/85216095/233825660-8c3cad82-aaf8-454b-b361-a2db7abc33b3.png)

I guess a better implementation should be to let users choose the language picker separately when they write a post?

**Comment by Alex0007** [comment]
@nhan000 you could check languages you know, not uncheck

**Comment by nhan000** [comment]
@Alex0007 well that is embarrassing. Somehow I didn't understand that feature. Thanks for pointing it out!
