### ISSUE TITLE
Opening the last post in a thread scrolls back to the first 

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#104]
**Describe the bug**

Using phanpy.social, when I visit [this (long) thread](https://phanpy.social/#/mastodon.social/s/110210993720490742) I use to dump images, I get automatically teleported to the first post of the thread. This, weirdly, only seems to happen with that thread in particular (although I haven't found a comparably long thread to test it out). 

**To Reproduce**
1. Go to https://phanpy.social/#/mastodon.social/s/110210993720490742
2. The last post of the thread will load (this might change if I add more posts 
3. Wait a few seconds. 
4. The page will load the whole thread and scroll back to previous posts. 

**Expected behavior**

The page should not scroll back. 

**Screenshots**

[Screen record from 2023-04-17 11.26.42.webm](https://user-images.githubusercontent.com/8617595/232516513-7690e55c-087e-4994-8760-e0dd467c8c5f.webm)

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir uilt on Ubuntu 20.04.6 LTS
 - Browser: Tested on Firefox and Chrome
 - Version: Firefox 112 and Chrome 112.0.5615.121 (same version!)

**Comment by cheeaun** [comment]
Wow thanks for the report, *that* is seriously a VERY long thread! 😱😱

**Comment by cheeaun** [comment]
Should be fixed now on production site.
