### ISSUE TITLE
Posts from external timeline don't open in sidebar

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#105]
**Describe the bug**

I added a shortcut to a local timeline from an external instance (https://mastodon.la/). It works great (thanks, it's great feature!) but when I click on posts in that column they don't open up in the sidebar. 

On the dev version I get an "Unable to process URL" error. 

Example post: 
https://phanpy.social/#/https://mastodon.la//s/110216039553116745
https://dev.phanpy.social/#/https://mastodon.la/s/110216039553116745

(Post on the instance: https://mastodon.la/@giorgiograppa/110216039553116745)

**To Reproduce**
1. Create a shortcut of a local instance (might be specific to https://mastodon.la/)
2. Click on any post. 
3. In the production site, nothing happens. In the dev site, get an "Unable to process URL" error. 

**Expected behavior**

The post should open in the sidebar. 

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir uilt on Ubuntu 20.04.6 LTS
 - Browser: Tested on Firefox 
 - Version: Firefox 112

**Comment by eliocamp** [comment]
Awesome. The workaround worked :) THanks!

**Comment by cheeaun** [comment]
Field validation added now on production site. Closing this for now.
