### ISSUE TITLE
Focus for scrolling is lost after context menu interaction

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#108]
In feed open context menu with right click, then press "Favourite". 
Context menu closes and now you can't scroll with browser hotkeys (like ArrowUp/Down buttons, or Cmd-ArrowDown)

Google Chrome, Mac OS

**Comment by Freeplayg** [comment]
Same things happens on Fedora w/ Firefox

**Comment by cheeaun** [comment]
Should be fixed now on production site.
