### ISSUE TITLE
Boost carousel shown in lists shortcuts even when disabled in settings

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#110]
**Describe the bug**

Both on prod and dev, I added a column with a list and disabled the boost carousel, but it still appears in the list column. 

**To Reproduce**
1. Add a shortcut with a list.
2. Disable boost carousel.
3. Wait until people on that list boost posts.
4. See them grouped in a carousel. 

**Expected behavior**

Boosts should appear as normal posts (with the usual bling)

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir uilt on Ubuntu 20.04.6 LTS
 - Browser: Firefox 
 - Version: Firefox 112

**Comment by cheeaun** [comment]
Should be fixed now on production site.
