### ISSUE TITLE
MastoHttpUnprocessableEntityError: Error processing thumbnail for uploaded media

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#111]
I'm trying to upload video file. Same video file can be uploaded with Elk just fine. 

After uploading video UI does multiple GET requests to `https://mstdn.social/api/v1/media/${id}`
and getting response:

```json
{"id":"110239769463848822","type":"video","url":null,"preview_url":"https://media.mstdn.social/media_attachments/files/110/239/769/463/848/822/small/718081930105feda.png","remote_url":null,"preview_remote_url":null,"text_url":null,"meta":{"original":{"width":1280,"height":720,"frame_rate":"8970000/298999","duration":29.909,"bitrate":5125579},"small":{"width":400,"height":225,"size":"400x225","aspect":1.7777777777777777}},"description":"test description","blurhash":"URD[@,RROjw|?*R:bDs7%Oo|wPWAXTkWnya$"}
```

And then on last request it gets:

```json
{"error":"Error processing thumbnail for uploaded media"}
```

Elk is not calling that endpoint at all

<img width="1243" alt="Screenshot 2023-04-22 at 05 03 54" src="https://user-images.githubusercontent.com/1143226/233753746-9ac614e6-e31e-4616-ae3d-65a2e6aa3419.png">

**Comment by cheeaun** [comment]
Are you able to upload the video on Elk (or any apps?). The upload success rate depends on your instance (current traffic load) + file size.

Also the multiple GET requests is a **must**, unfortunately. The status post will only work **if** all the media are **processed** (Uploaded doesn't mean it's done processing).

**Comment by Alex0007** [comment]
@cheeaun 

Upload is

`POST https://mstdn.social/api/v2/media`
(both used by Phanpy and Elk)

After upload is done: 

 - Elk makes no additional requests
 - Phanpy start making `GET https://mstdn.social/api/v1/media/{media.id}` requests (and gets that error)

**Comment by Alex0007** [comment]
@cheeaun 
In case you need test file that is failing to upload: [link](https://media.mstdn.social/media_attachments/files/110/307/094/629/109/151/original/784205711653a99f.mp4)

Instance i'm uploading to: mstdn.social

**Comment by Alex0007** [comment]
Issue no longer reproducible

**Comment by Alex0007** [comment]
Issue appeared again. Using Mastodon Android application is working fine for videos uploading
