### ISSUE TITLE
Phanpy stops working after opening Notifications

### ISSUE THREAD

**Issue by LukaszH77** [cheeaun/phanpy#112]
**Describe the bug**
- Which site: dev.phanpy.social

**To Reproduce**
1. Open Notifications
2. Only a handful of notifications are loaded
3. You can click on anything, the URL will change but nothing else happens

**Expected behavior**
All the notifications should load and clicking parts of UI should work

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 111 and Chrome 112

**Smartphone (please complete the following information):**
 - Device: Moto G7
 - OS: Android
 - Browser: Chrome 112

**Comment by cheeaun** [comment]
@LukaszH77 can try it again (reload dev site)? I suspect there's a poll in your Notifications. If not, I probably missed something… 🫠

**Comment by LukaszH77** [comment]
It works now, thank you!
