### ISSUE TITLE
Why does Phanpy ask to "see text and images copied to the clipboard"?

### ISSUE THREAD

**Issue by nhan000** [cheeaun/phanpy#114]
![image](https://user-images.githubusercontent.com/85216095/233889866-9b834a34-ae01-412c-95f7-7a361513c406.png)

I've ran into this on a few websites. Usually, I just assumed malice and blocked the request. However, I was surprised to see Phanpy also has this request today.

Could you explain why Phanpy needs this permission, and should I allow or block and what's the implications? Thank you!

**Comment by cheeaun** [comment]
May I know which browser is this?

So far clipboard access is needed when you need to paste text or images into the composer, for posting.

**Comment by nhan000** [comment]
it's Edge on Windows 11. All updated.

**Comment by cheeaun** [comment]
Another question, when does the prompt appear? Is it on first load on the home page, or first load of the composer page, or when you start pasting something? Thanks

**Comment by nhan000** [comment]
I don't really remember what trigger that request and I haven't seen it since then. 

I'll close the issue for now and will open later if I have more details to share. Thank you!
