### ISSUE TITLE
Add a standard license notice

### ISSUE THREAD

**Issue by nemobis** [cheeaun/phanpy#115]
Thanks for developing phanpy under a free license. I see https://cheeaun.mit-license.org/ mentioned in the README, however it would be nice to have it also as a `LICENSE` file so that the repository is recognised as being free software. (GitHub itself currently doesn't pick up its license.)

**Comment by cheeaun** [comment]
Cool, added via GitHub's license template wizard https://github.com/cheeaun/phanpy/commit/841737242fe581b5da607ed911ca5b59b8fa9e32
