### ISSUE TITLE
"Cloak" mode not cloaking all posts in a thread

### ISSUE THREAD

**Issue by jsvensson** [cheeaun/phanpy#121]
**Describe the bug**
Bug on phanpy.social (not dev)

**To Reproduce**
- Enable cloak mode
- A thread with a certain number of posts (only seen with 5 which was what I had in my timeline at the time) will only show the first and last post in the thread as cloaked, post 2-4 in the thread remain uncloaked.

**Expected behavior**
- All posts in the thread should be cloaked.

**Screenshots**

![image](https://user-images.githubusercontent.com/450287/235310399-925265bf-6c08-4de0-8c95-54df19178628.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Arc Browser (Chromium-based)
 - Version:
   - Arc Browser: Version 0.101.2 (38549)
   - Chromium Engine Version 112.0.5615.137

**Comment by cheeaun** [comment]
Should be fixed on production now.
