### ISSUE TITLE
context menu pops up when scrolling on mobile

### ISSUE THREAD

**Issue by ghosttie** [cheeaun/phanpy#127]
When scrolling on mobile the context menu keeps popping up which interrupts the scrolling.

- phanpy.social

**To Reproduce**
1. Go to Home
3. Scroll down
5. Context menu pops up

**Expected behavior**
The context menu only pops up when the globe is tapped

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 13
 - Browser: Chrome
 - Version: 112

**Comment by cheeaun** [comment]
Should be fixed on prod now 🙇‍♂️
