### ISSUE TITLE
Compose button goes away when navigating away from Home

### ISSUE THREAD

**Issue by dvdjaco** [cheeaun/phanpy#128]
**Describe the bug**
On phanpy.social, the "Compose" button on the bottom right corner disappears if you browse away from the Home view.

**To Reproduce**
1. Log in to phanpy.social
2. Click on a different view (e.g. Notifications, Search, Mentions...)
3. The Compose button disappears.

**Expected behavior**
The Compose button should be visible on all main views. Alternatively, it could be added to the "Shortcuts options".

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Browser: Firefox 113.0b9

**Comment by cheeaun** [comment]
Should be available on production now.
