### ISSUE TITLE
Announcements not signalled

### ISSUE THREAD

**Issue by timbray** [cheeaun/phanpy#129]
**Describe the bug**
I'm an admin and mod on a medium-small site and announcements are pretty important ("we're going to have downtime tomorrow night" / "yes, we know about the spam storm"). phanpy doesn't notify when there's a new one. (and also I think doesn't even provide a way to see them?)
- Which site: phanpy.social

BTW I'm a huge fan of phanpy not pestering me with notifications about mentions or anything else. Excellent UI.  But announcements could be really important and I think just bypassing them is probably wrong.

**Comment by cheeaun** [comment]
Should be fixed on production now.
