### ISSUE TITLE
Main menu won't open on Chrome for Android

### ISSUE THREAD

**Issue by HughsterUK** [cheeaun/phanpy#134]
**Describe the bug**
On both phanpy.social and dev.phanpy.social viewed on Chrome for Android in portrait orientation, when on any page other than Home, the main menu won't stay open unless at the top of the page and instead scrolls the page upwards with each attempt to open it.

**To Reproduce**
1. On Chrome for Android in portrait orientation, go to phanpy.social or dev.phanpy.social
2. Select any view from the main menu other than "Home"
3. Try to open the main menu; it opens correctly
4. Scroll down the page, and then slightly up so that the top menu bar shows
5. Try to open the main menu; it opens but then immediately closes, and the page scrolls slightly up

**Expected behavior**
The main menu should stay open.

**Screenshots**
Video showing the behaviour: https://github.com/cheeaun/phanpy/assets/132479092/df247906-26b0-46be-8c27-486c7c57dd75

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 12 (build SP1A.210712.016.C2)
 - Browser: Chrome (version 113.0.5672.77)

**Comment by cheeaun** [comment]
Potential fix deployed in production.

**Comment by HughsterUK** [comment]
This fixed the issue for me! Many thanks.
