### ISSUE TITLE
Profile picture menu icon isn't updated after changing

### ISSUE THREAD

**Issue by LukaszH77** [cheeaun/phanpy#148]
**Describe the bug**
- Which site: dev.phanpy.social

**To Reproduce**
1. Change the profile picture on one of your Mastodon accounts
2. Open Phanpy
3. It shows either the old PFP or a grey square.

**Expected behavior**
Changed PFP in the menu

**Screenshots**
![Zrzut ekranu z 2023-05-22 18-04-15](https://github.com/cheeaun/phanpy/assets/121253127/3c1277ea-2043-4d43-ba68-6e6ad534c61e)
![Zrzut ekranu z 2023-05-22 18-05-43](https://github.com/cheeaun/phanpy/assets/121253127/d7008c82-a328-438d-91d4-ebbbda77fc7f)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Browser: Firefox
 - Version: 113

**Comment by cheeaun** [comment]
Try open "Accounts…" sheet and double-click on your account's avatar.

**Comment by LukaszH77** [comment]
That did the trick, thank you.

**Comment by cheeaun** [comment]
@LukaszH77 great to know it works! Anyway, this is still kind of a bug; Phanpy cache the account and won't refetch every time - probably I will need to figure this out.

I'm also not sure how you could see the grey square? I assume the old avatar has been deleted from your instance server?

**Comment by LukaszH77** [comment]
I think I could see the old PFP when it was cached and then the grey square after hard refreshing Phanpy.

**Comment by jeffsikes** [comment]
Came here to report the same, and the account / double click the icon trick worked.

Tried a hard refresh (Shift + Refresh Icon click) and that didn't work. I'm assuming if I logged all the way out and back in, that would refresh it.

<img width="290" alt="image" src="https://github.com/cheeaun/phanpy/assets/6627582/05e5f3fd-dedd-4785-b5f7-852dda46d278">

**Comment by cheeaun** [comment]
Should be fixed on prod now 🙇‍♂️
