### ISSUE TITLE
broken by language "startrek_it"

### ISSUE THREAD

**Issue by felix9** [cheeaun/phanpy#154]
visit https://phanpy.social/#/mastodon.social/s/110486304540817373?view=full

page shows loading and never finishes.

console error is `Uncaught (in promise) RangeError: invalid_argument`

error location is localeCode2Text.jsx:4
```js
export default function localeCode2Text(code) {
  return new Intl.DisplayNames(navigator.languages, {
    type: 'language',
  }).of(code);
}
```
The value of `code` is "startrek_it", which causes the RangeError.

**Comment by cheeaun** [comment]
Should be fixed now on production (possibly need to reload), can check it out 🙏

**Comment by felix9** [comment]
works! thanks!
