### ISSUE TITLE
Media sometimes displays tiny when opened

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#155]
**Describe the bug**

When opening media (images, videos) sometimes the size of the media is tiny. Clicking on it multiple times changes it size somewhat randomly. 

This happens on Firefox, but not on Chrome. 

**To Reproduce**
1. Go to a post with a picture or video
2. Click on it

**Expected behavior**
The picture or video should be visible and use all the screen.

**Screenshots**

[Screen record from 2023-06-04 16.40.36.webm](https://github.com/cheeaun/phanpy/assets/8617595/0f20d143-bab4-476f-ab91-e9d01c5941fe)

**Desktop (please complete the following information):**
 - OS:  elementary OS 6.1 Jólnir Built on Ubuntu 20.04.6 LTS
 - Browser Firefox 
 - Version 113.0.2 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cheeaun** [comment]
@eliocamp is it possible to provide the link to that post? (so that I can replicate this issue on my side). If you're concerned about privacy, you can private mention me on [cheeaun@mastodon.social](https://mastodon.social/@cheeaun) 🙇‍♂️

**Comment by eliocamp** [comment]
Hi! I think I might have more information regarding this bug. I generally use my laptop with a second screen which I set up as the primary screen. But I noticed that I wasn't experiencing this issue when only using one monitor. Maybe some part of the code is computing the screen size to display media and getting the wrong size when there are multiple screens?

**Comment by eliocamp** [comment]
Well, scratch that. I'm now using the same laptop with just one screen and it's happening again. 😭

**Comment by cheeaun** [comment]
@eliocamp is it possible to try a different browser?

**Comment by eliocamp** [comment]
Chrome doesn't seem to have the issue.

**Comment by eliocamp** [comment]
I don't know if you changed something, but it now seems to be working correctly!

**Comment by cheeaun** [comment]
@eliocamp I didn't… change anything 😂 I suspect the browser got updated?

**Comment by eliocamp** [comment]
Maybe! I'm now on Firefox 121.0 and I'm not experiencing the issue. Since the issue was always sporadic, I'll give it a few days and if it doesn't return, I'll close the issue.

**Comment by eliocamp** [comment]
The bug still hasn't returned after several sessions, so I'm closing this. Thank you for all the work! 🤣
