### ISSUE TITLE
very slow when loading long threads

### ISSUE THREAD

**Issue by felix9** [cheeaun/phanpy#159]
there are about 600 posts in this thread, and this is the last one (at the moment):
https://phanpy.social/#/mastodon.social/s/110496516327983683

on my laptop, loading that makes phanpy unresponsive for about a minute, and Chrome gives me the "page unresponsive" popup several times. it's even slower on my phone.

**Comment by cheeaun** [comment]
Should be fixed now on production (possibly need to reload), can check it out 🙏
