### ISSUE TITLE
Hashtag shortcuts with multiple hashtags don't load all the relevant posts

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#169]
**Describe the bug**

If I add a hashtag shortcut and I add more than one hashtag, then the shortcut doesn't list all relevant posts. 

**To Reproduce**
1. Create a new shortcut with one hashtag (i.e. "#rstats"). 
2. Create another shortcut with the same hashtag plus another one (i.e. "rstats datadon")
3. Look back at both columns posts. 
4. Eventually you will find that the second column is missing old posts that the first column does show. 

**Expected behavior**

All posts with any of the hashtags should be shown. 

**Screenshots**

This was taken on the 19 of June. The "rstats datadon" shortcut shows all the posts up to 5 hours before and then jumps 10 days even though there are many rstats posts in between. 

![image](https://github.com/cheeaun/phanpy/assets/8617595/9d7a9a58-22fc-4659-840f-4cb1b319949d)

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir Built on Ubuntu 20.04.6 LTS
 - Browser: Firefox 114.0.1 (64-bit) and Chrome 114.0.5735.133 (also on mobile with chrome)

**Comment by cheeaun** [comment]
@eliocamp should be fixed in production now (possible need to reload), can check it out if it's still not working 🙏

**Comment by eliocamp** [comment]
Seems to be working now. Thanks!
