### ISSUE TITLE
Load Serverside user Post Defaults

### ISSUE THREAD

**Issue by sandboxgangster** [cheeaun/phanpy#171]
**Describe the bug**
It would be a problem if Phanpy would take over the user settings from the server, e.g. the settings for posting (public, unlisted ...).

For me, Phanpy always wants to post publicly, although "private" is set on the server side.

**To Reproduce**
---

**Expected behavior**
Phanpy lists the Server-side User defaults and sets them automatically.

**Screenshots**
---

**Desktop (please complete the following information):**
---

**Smartphone (please complete the following information):**
---

**Additional context**
---

**Comment by cheeaun** [comment]
@sandboxgangster this should be fixed by now, can check/test it out 😄

**Comment by sandboxgangster** [comment]
Works THX
