### ISSUE TITLE
"Search > Posts" returns max 40 results

### ISSUE THREAD

**Issue by HughsterUK** [cheeaun/phanpy#174]
**Describe the bug**
On both phanpy.social and dev.phanpy.social, when you try to use the "Search > Posts" feature, the maximum number of results for any term is 40. There is no infinite scroll or button to load more results. The default Mastodon web UI's "Search > Posts" view provides a "load more" button to allow you to keep returning results.

**To Reproduce**
1. Go to Main Menu > Search
2. Search for a common word, e.g. "but" or "with", and choose the "Posts" tab beneath the search box
3. The max number of results is 40, with no option to load more

**Expected behavior**
The page should either infinitely scroll (as with hashtag search results) or show a "load more" link at the bottom (as with the default Mastodon web UI)

**Desktop (please complete the following information):**
 - OS: Windows 10 (version 22H2, OS Build 19045.2965)
 - Browser: Chrome (version 114.0.5735.110)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 12 (build SP1A.210712.016.C2)
 - Browser: Chrome (version 114.0.5735.130)

**Comment by cheeaun** [comment]
Should be fixed by now 🙏

**Comment by HughsterUK** [comment]
Unfortunately still only 40 results here, both dev and main 😕

**Comment by cheeaun** [comment]
@HughsterUK may I know what's the instance that you're using? Also possible if you can check which version of Phanpy you're running (nav menu → Settings → About → Last build)?

**Comment by HughsterUK** [comment]
Instances:
mastodon.social
universeodon.com

Last builds:
375da8d (main)
fa21eec (dev)

**Comment by HughsterUK** [comment]
I get 38(?) results for that, with "The end" showing at the bottom.

**Comment by cheeaun** [comment]
Should be fixed on prod now 🙇‍♂️
