### ISSUE TITLE
Back/forward browser two-finger touchpad gestures are not working

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#177]
**Describe the bug**
- Which site: phanpy.social

**To Reproduce**
1. Go to Phanpy
1. Try to go forward/backward with two-finger touchpad gestures

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc
Version 0.110.1 (39837)
Chromium Engine Version 114.0.5735.198

**Comment by cheeaun** [comment]
@Alex0007 may need to know more details on the steps here 🙏 e.g.

1. Go to Phanpy
2. Click on something? Go to a page? **←**
3. Swipe back with two-finger

**Comment by Alex0007** [comment]
Hey @cheeaun. 

Oh, i can see it's working in some conditions. So here is reproduction details

1. Go to profile page
1. Open post
1. Swipe back with two-finger from opened post body

Same is applicable to your own posts in feed view

<img width="577" alt="image" src="https://github.com/cheeaun/phanpy/assets/1143226/b12f442c-86d8-4902-b0ee-3fcffae3d7d5">

**Comment by Alex0007** [comment]
Also applicable to boosted posts and posts that are part of thread

**Comment by cheeaun** [comment]
@Alex0007 need your help testing this. Try 2-finger swipe back when the cursor position is on the backdrop (darker left side of the post) vs when the cursor is on the post itself (right side, within the post) 🙇‍♂️

**Comment by Alex0007** [comment]
@cheeaun 
It works from backdrop (90% of the time) in Chrome. Not working from post itself.

Now it works in Arc Browser (both from backdrop and post)

**Comment by Alex0007** [comment]
I think it is fixed?
