### ISSUE TITLE
Bug with viewing multiple images on Webkit2GTK-4.1

### ISSUE THREAD

**Issue by StandingPadAnimations** [cheeaun/phanpy#181]
**Describe the bug**
__*Context*__
I should get something out of the way: I found this when making a Tauri wrapper for Phanpy (https://github.com/cheeaun/phanpy/discussions/180), but at this point I believe it's a website issue in `Webkit2GTK-4.1` (roughly equivalent to Safari 13+). I did edit the `vite.config.js` file but that's it, everything else has been untouched.

Modified portion: 
https://github.com/StandingPadAnimations/phanpy-tauri/blob/a63d4afefdbdf69cbf0a608e7aee8222dc3b89ab/vite.config.js#L95-L99

__*Actual Bug*__
When trying to view a post with multiple images, the image clicked on will stay and requires a page reload to fix. It also can make it so when any post is clicked, the image is viewed.

**To Reproduce**
1. Open Phanpy in a browser that uses `Webkit2GTK-4.1`
2. Click on an image in a post with multiple images
3. Deal with a stuck image until reload

**Expected behavior**
Clicking on a single images on a post with multiple images should bring up some arrows like it does on Firefox and Chrome

**Screenshots**
Video of me clicking an image in a post with a single image vs an image in a post with multiple images. In the latter, no matter how much I click or press ESC, the image won't exit

https://github.com/cheeaun/phanpy/assets/75058058/19023146-d555-4ef7-8efa-c1a7aaba434e

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Tauri app, but Vite is set to build for Safari 13
 - Version: 13

**Additional context**

**Comment by StandingPadAnimations** [comment]
Oh boy, we got this funny bug as well with the timeline, should I file this under a separate issue?
![image](https://github.com/cheeaun/phanpy/assets/75058058/139ed540-ba17-4a6d-ada2-fc3db2506b36)

**Comment by cheeaun** [comment]
Hi, pretty cool that you're making a Tauri wrapper! 🙇‍♂️

I don't have any experience with Tauri, does it have some sort of debugging/dev tools? To set expectations, I won't have time to debug this on my side unfortunately.

**Comment by StandingPadAnimations** [comment]
> I don't have any experience with Tauri, does it have some sort of debugging/dev tools?
Yep, thankfully it does

Looking into it on a debug build of the Tauri app (but still using the production build), there doesn't seem to be any errors related to the multiple images bug. It also seems like eventually the other parts of the image viewer (alt text, arrows to view other images, etc) appear eventually and return back to normal (if the user waits for a long time). After the initial wait time, the bug seems to go away (well until one expands on the post and clicks an image again).

Based on this, I feel like this has something to do with `Webkit2GTK-4.1`'s ability to load JS/CSS, I'll have to look into this further

**Comment by StandingPadAnimations** [comment]
Alright, found the culprit, it seems to be hardware accelerated compositing. `export WEBKIT_DISABLE_COMPOSITING_MODE=1` seems to fix the issue.

I'll close this issue now since it's a Webkit bug

**Comment by StandingPadAnimations** [comment]
Yep, it's [definitely a WebKit issue](https://blogs.igalia.com/carlosgc/2017/02/10/accelerated-compositing-in-webkitgtk-2-14-4/), known as well
> Startup and resize slowness: The threaded compositor makes everything smooth and performs quite well, except at startup or when the view is resized. At startup we need to create the OpenGL context, which is also quite slow by itself, but also need to create the compositing thread, so things are expected to be slower. Resizing the viewport is the only threaded compositor task that needs to be done synchronously, to ensure that everything is in sync, the web view in the UI process, the OpenGL viewport and the backing store surface. This means we need to wait until the threaded compositor has updated to the new size.

It's OpenGL to blame
