### ISSUE TITLE
Boosting does not work from "Reboosted" card

### ISSUE THREAD

**Issue by natsukagami** [cheeaun/phanpy#189]
**Describe the bug**
Hitting Boost from the post's menu on the Reboost panel just closes the menu.
- Which site: dev.phanpy.social
- Which instance: mstdn.jp

**To Reproduce**
1. Go to Home Timeline
2. Check any reboosted carousel post
3. Try to boost

**Expected behavior**
New "Confirm Boost" menu shows up?

**Screenshots**
![image](https://github.com/cheeaun/phanpy/assets/9061737/8df8d760-f5ab-420e-b0f8-4e23627f2d9e)

Clicking Boost here only closes the menu.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 115

**Smartphone (please complete the following information):**
 - Device: iOS
 - OS: 16
 - Browser: Stock Safari

**Comment by cheeaun** [comment]
@natsukagami thanks for the fast bug report! I kinda fixed it (maybe), can check it out? 🙏

**Comment by natsukagami** [comment]
No luck yet, I'm seeing the same behaviour on Firefox and Vivaldi :( 
I tried both https://dev.phanpy.social and `npm run dev`ing the main branch.

**Comment by cheeaun** [comment]
@natsukagami I've also tried on Firefox 102.0.1 on Ubuntu 22.04.2 LTS (I couldn't upgrade Firefox here), and can't replicate your issue 😩 I personally don't think it's a Mastodon thing.

Is it possible if you can screen record and show it here? Thanks! 🙏

**Comment by natsukagami** [comment]
Sure! This is on Firefox 115 on NixOS 


https://github.com/cheeaun/phanpy/assets/9061737/385fad8a-3245-408f-866e-69f1c1f2b6a7

**Comment by cheeaun** [comment]
@natsukagami thanks for clarifying! The screen record is **super useful**, I didn't test the menu that pops out from the timestamp. FYI, you can trigger the menu by right-clicking (mouse) or long-pressing (touch) on the post too (which is what I was testing 🙈)

Will be closing this. Feel free to open another issue if the bug happens again 🙏
