### ISSUE TITLE
Random posts are getting automatic translations

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#191]
**Describe the bug**

For some posts by some users I'm seeing the automatic translation directly on my timeline. 

**To Reproduce**
1. Go to this user's profile: https://phanpy.social/#/mastodon.social/a/110527903972711377
2. Scroll through their posts
3. Some posts are accompanied by an automatic translation, others don't. 

The automatic translation disappears if I hide the translation button for Spanish. 

**Expected behavior**

Either all or none of the posts should be translated automatically (in my case, I think the correct behaviour is to not show automatic translations unless I click on the translate button). 

**Screenshots**

![image](https://github.com/cheeaun/phanpy/assets/8617595/d7969c85-75e7-4a9e-a2a9-13190f314798)

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir.
 - Browser: Firefox 115.0.2  and Chrome 115.0.5790.98

**Comment by lamnatos** [comment]
Same here, I think it translates anything that is **not** defined as English (even if it's evidently English). It feels like it's not taking into account the translation settings.

**Comment by cheeaun** [comment]
Thanks for feedback! I've disabled the feature now and made it manual opt-in.

This experiment is not perfect yet 😉. Few issues/notes:
- I've made it to only work for short posts (no content warning, no media, no poll) as it might take up a lot of (vertical) space.
- There's unfortunately *a lot* of posts with wrongly-set languages (e.g English post but set as non-English 😩; at least for me on my timeline). While some (non-Mastodon instances) don't even have `language`…
- The auto-translation is also throttled as to not overwhelm the translation API, and also to prevent too much jumpy layouts.

@lamnatos the auto-inline-translation *should* follow the targeted language set in Settings (refer to "Translate to [language]" field). If not, please report here 🙏

@eliocamp I know it looks weird with some posts translated and some not 🤣. I'd like it to be a subtle "progressive enhancement"; if it's there, it's cool, if it's not there, you'll still be able to manual-translate it.

**Comment by eliocamp** [comment]
Hehe, I understand. 

My two cents is that the inconsistency is very distracting. So I'd prefer either for the client to either auto-translate everything, or auto-translate nothing.  

I generally don't want autotranslation at all, but I do appreciate having the option. For languages I'm not fluent on (German, basically), reading the original helps me practise but having the button to translate if needed is super helpful. 

And yes, a lot of posts are badly tagged. I think it's mostly people that post in one language most of the time and don't change it when they post in another.

**Comment by eliocamp** [comment]
I think this is solved in the latests dev, so I'll close the issue. I hope that's OK.
