### ISSUE TITLE
When vieweing a post with multiple images, clicking on the arrows disables keyboard navigation

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#198]
**Describe the bug**

What it says on the title. :)

**To Reproduce**
1. Open a post with more than one image. 
2. Press the left or right arrow keys, the images will scroll. 
3. Now click on one of the arrows to scroll again. 
4. Press the left or right arrow keys, not the images will not scroll

**Expected behavior**
Images should always scroll when with the arrow keys.

**Desktop (please complete the following information):**
 - OS: elementary OS 6
 - Browser Firefox and Chrome 
 - Version 115.

**Comment by graue** [comment]
@eliocamp does this still happen for you? I can't repro anymore, so I think it might be fixed.

**Comment by eliocamp** [comment]
Nope, I think this was fixed.
