### ISSUE TITLE
Returning home from Trending tab shows empty page

### ISSUE THREAD

**Issue by brawaru** [cheeaun/phanpy#199]
**Describe the bug**
If you loaded Phanpy via trending page, trying to go to home timeline results in an empty page, with only post button showing.

- Which site: dev.phanpy.social and phanpy.social
- Which instance: mstdn.social

**Steps to Reproduce**
1. Load Phanpy in Trending tab OR go to Trending and reload page.
2. Click on navigation menu button and select Home.

**Expected behavior**
Home timeline shows up as usual.

**Actual behavior**
Page goes blank with an exception to posting button. You can navigate back using Back button in your browser, but you won't be able to access Home page no matter what you do.

**Screenshots**

https://github.com/cheeaun/phanpy/assets/10401817/548e9628-752c-46cf-af8b-55bd50b636f9

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 115.0.2

**Additional context**
There don't seem to be any errors in the console.

**Comment by cheeaun** [comment]
@brawaru 3 questions:

1. If you reload Home, does the timeline show?
2. Is this bug only happen when pressing Back from Trending page? How about other pages?
3. What does the URL/address bar show when pressing Back (to Home) from Trending page?

Thanks! 🙏

**Comment by brawaru** [comment]
1. If you go to Home and reload, it shows just fine, and then also works perfectly, even if you go to Trending and then back Home. It only does this when you start your ‘session’ with ~~Trending page~~ any page that's not Home. Only noticed this issue because Firefox pinned link to Trending among new tab shortcuts 😄 
2. Oh, actually, it seems that any page that is not Home breaks it! Tested with Followed Hashtags, Notifications, Search, Profile. If you load any of these pages first and then try to go Home it breaks. Great that you asked that.
3. The URL changes to `https://phanpy.social/#/` upon going Home.

https://github.com/cheeaun/phanpy/assets/10401817/5324a8ea-0be9-40dd-b1a1-604bd5145af6

**Comment by cheeaun** [comment]
@brawaru this is a little difficult for me to fix as I'm unable to reproduce this on my side. 😩

Is it possible if you could try this on incognito mode on Firefox or a different browser, and see if the same bug happens? 🙏

**Comment by brawaru** [comment]
I have found the culprit! Enabling `layout.css.has-selector.enabled` in `about:config` seems to cause this, and I feel like this is Firefox's bug, because when the page is blank, opening DevTools immediately reveals all context. Even if the DevTools are in background and you retry reproduction steps, when you hover over a single element in DevTools in elements tree, the content immediately appears.

The theme I use enabled this preference, and then it persisted, so I didn't even think about this. But resetting all preferences and re-applying them one by one lead to this discovery. Really really sorry for wasting your time with this one. I really should've tested with empty profile before creating the issue.

(btw this also fixed the bug where context menu would make the whole page unclickable, and now that I remember that this was also fixable by simply opening DevTools, it *clicks*; why I didn't check with empty Home, I dunno, this seems so obvious now)
