### ISSUE TITLE
Keyboard navigation between photos is flaky

### ISSUE THREAD

**Issue by graue** [cheeaun/phanpy#204]
**Describe the bug**
Left arrow key to go back to previous photo in a set sometimes doesn't work

- Which site: phanpy.social
- Which instance: carfree.city

**To Reproduce**
1. Open a toot with 3 or 4 photos
2. Click on the first photo to zoom in
3. Press right arrow key repeatedly to go to the last photo
4. Attempt to return to the first photo by pressing left arrow key repeatedly

It gets stuck on the second-to-last photo and will proceed no further.

**Expected behavior**
Phanpy should go back to the first photo

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Firefox
 - Version: 116

**Comment by graue** [comment]
I see #198 looks similar and might be related, but this happens without clicking on the arrows.

**Comment by eliocamp** [comment]
Can confirm. 

In 4-image posts I can navigate with the keyboard between images but I can't go neither to the last one nor to the first one. 

Smells like a off-by-one error to me 🐽.

**Comment by aggregat4** [comment]
I have a similar problem in that I often can't move past the second image: I can navigate from the first to the second and back again. But not to the third. This is also using the arrow keys. Example post where this happens for me on Firefox is: https://phanpy.social/#/c.im/s/111482990463470223

**Comment by cheeaun** [comment]
@eliocamp @aggregat4 what's your Firefox version and the OS used?

Is this when the image carousel is displayed together with the post or just the image carousel itself?

**Comment by eliocamp** [comment]
I'm on 120.0 (64-bit). 

It happens in both scenarios.

**Comment by aggregat4** [comment]
Firefox 120.0 on Arch Linux, kernel 6.6.2-arch1-1.

Can confirm the problem with both with carousel only and with the post along side it.

Tried it in a private browsing window as well to rule out extensions interfering.

The developer console has some errors, but they are all GET requests on resources failing. Specificall 2 resources:

- https://static.cloudflareinsights.com/beacon.min.js  (CORS Request blocked)
- some s3 avatar images are missing

**Comment by graue** [comment]
I stopped seeing this bug. It must be fixed. Thanks!
