### ISSUE TITLE
pull down refreshes the entire app, instead of just refreshing the feed

### ISSUE THREAD

**Issue by plaidman** [cheeaun/phanpy#207]
**Describe the bug**
Chrome (and other browsers) on mobile often come with a pull-down-to-refresh feature. This will refresh the whole app, and lose your place in the home feed if you do it on some other view.
- Which site: dev.phanpy.social
- Which instance: infosec.exchange (though I suspect that doesn't matter)

**To Reproduce**
1. Go to your home feed
2. Scroll down a few posts
3. Click on a post
4. Pull down on the app to refresh
5. Press back to go back to home feed
6. Notice the home feed is back at the top because the app refreshed

**Expected behavior**
The app should keep your spot in the home feed, and refresh your current view, instead of reloading the entire app.

**Smartphone (please complete the following information):**
 - Device: Samsung S23
 - OS: Android
 - Browser: chrome PWA
 - Version: 115

**Additional context**
This will probably happen in other browsers too. I found [an article on how to disable pull down to refresh](https://stackoverflow.com/questions/69261011/disable-pull-to-refresh-in-ios-15-safari/69589919#69589919) in chrome, safari 16+, and safari 15- using CSS rules.

```
/* prevent pull-to-refresh for Safari 16+ */
@media screen and (pointer: coarse) {
  @supports (-webkit-backdrop-filter: blur(1px)) and (overscroll-behavior-y: none)  {
    html {
      min-height: 100.3%;
      overscroll-behavior-y: none;
    }
  }
}

/* prevent pull-to-refresh for Safari 9~15 */
@media screen and (pointer: coarse) {
  @supports (-webkit-backdrop-filter: blur(1px)) and (not (overscroll-behavior-y: none))  {
    html {
      height: 100%;
      overflow: hidden;
    }
    body {
      margin: 0px;
      max-height: 100%; /* or `height: calc(100% - 16px);` if body has default margin */
      overflow: auto;
      -webkit-overflow-scrolling: touch;
    }
    /* in this case to disable pinch-zoom, set `touch-action: pan-x pan-y;` on `body` instead of `html` */
  }
}

/* prevent pull-to-refresh for Chrome 63+ */
body{
  overscroll-behavior-y: none;
}
```

**Comment by plaidman** [comment]
I tested the `overscroll-behavior-y: none;` for chrome on my phone and it seems to work well. I don't have an apple phone to test the safari solutions.

**Comment by cheeaun** [comment]
🤔 Hmm this is quite debatable. This could be a bug for your use-case but disabling pull-down-to-refresh can be a bug itself too for other/different use-cases/expectations.

On iOS, pull-down-to-refresh only works in the browser, **not** in PWA. On Android, you're right, pull-down-to-refresh works in both the Chrome browser **and** PWA 🤔

Technically the safe option is probably this; disable pull-down-to-refresh only when in PWA **and** on the post page. What do you think?

**Comment by plaidman** [comment]
I think this can be in more than just the post screen. For instance if you're browsing through someone's profile posts and accidentally scroll too far past the top to refresh the app. Maybe it would be possible to create an option in the settings?

**Comment by plaidman** [comment]
Or maybe only allow pull to refresh if there are no pages in the previous history?

**Comment by cheeaun** [comment]
Added a fix on dev site, but only for PWA (standalone mode). Seem to work on my Pixel 3, Chrome PWA.

Notes:
- I was initially hesitant to add this fix, as it's quite debatable based on use-cases.
- If it's really a bug, it won't just affect Phanpy, but all other PWAs too, so generally should be a Chrome bug.
- Did a little research and found these (very old) discussions/issues:
  - https://bugs.chromium.org/p/chromium/issues/detail?id=456515 (2015, wontfix)
  - https://bugs.chromium.org/p/chromium/issues/detail?id=465423 (2015, open, last modified 2022)
  - it's evident that even Chrome devs aren't quite sure if it's a bug or a feature 🤦‍♂️
- IMO, if iOS PWA doesn't have pull-to-refresh, should be fine on Chrome PWA too. We'll observe if this fix is reported as a bug in the future 🤞

**Comment by plaidman** [comment]
I noticed it was in dev this morning, thank you! And thanks for the research, it was pretty interesting how many wished for it to be like iOS. Given that I think it's a great solution.
