### ISSUE TITLE
multi-picture dots are misaligned

### ISSUE THREAD

**Issue by plaidman** [cheeaun/phanpy#209]
**Describe the bug**
The dots at the top of the image UI on mobile are misaligned vertically. Part of me didn't want to report this because it's super pedantic, but the rest of the site is so impeccably designed that this seemed like something you might want to fix. It's really not something that reduces the functionality, but it does seem like something that would be pretty easy.
- Which site: dev.phanpy.social
- Which instance: infosec.exchange

**To Reproduce**
1. Click on an image in a post with multiple images.
2. Tap on the screen to show the image UI.
3. Notice the image carousel dots are not aligned vertically.

**Expected behavior**
The image count dots should have equal space on the top and bottom.

**Screenshots**
![Screenshot_20230804_222033_Firefox](https://github.com/cheeaun/phanpy/assets/1633027/e5708679-aa9d-4094-9478-550d08d24475)

**Smartphone (please complete the following information):**
 - Device: Samsung S23
 - OS: Android
 - Browser: Chrome PWA
 - Version: 115

**Comment by cheeaun** [comment]
Should be fixed on prod now 🙇‍♂️
