### ISSUE TITLE
Repeated double-tap should zoom out in photo view

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#213]
**Current behaviour**: 
Repeated double tap on photo continues to increase zoom

**Proposed behaviour**:
Second double tap should revert zoom back to original. 

 - That big zoom value makes no sense anyway
 - It will allow to zoom-out with single hand (currently impossible)

**Comment by cheeaun** [comment]
Should be fixed on prod now 🙇‍♂️

**Comment by Alex0007** [comment]
@cheeaun i really don't like 5 levels of zoom :(

zoom-in/zoom-out taps should be enough in my opinion. Other zoom levels can be reached with 2 fingers swipe. It's too hard to exit from zoom with so many taps. 

Can this be reconsidered?
