### ISSUE TITLE
Defaults for Post Settings (e.g. Lang)

### ISSUE THREAD

**Issue by sandboxgangster** [cheeaun/phanpy#215]
**Describe the bug**
Hello, I use GoToSocial and in the latest Phanpy version there doesn't seem to be a default for the language settings for posts anymore, which means I get an error when I want to send a post, but as soon as I set the language of the post it works again.

GoToSocial has no Settings for this.

**To Reproduce**
Send Post with GoToSocial as Instance

**Expected behavior**
It would be nice if settings that are read by the instance get a default if they are not available.

**Error Message**
MastoHttpUnexpectedError: Bad Request: json: cannot unmarshal bool into Go struct field AdvancedStatusCreateForm.language of type string

**Desktop (please complete the following information):**
Chromium
GoToSocial 11.0.0 - RC2
Phanpy 8b74a32

**Comment by cheeaun** [comment]
Can try the latest (dev) version? I suspect this https://github.com/cheeaun/phanpy/commit/ac8a4c7fbff4c2673e9ff04cc02852e1b99bf3df could have fixed it 🙏

**Comment by sandboxgangster** [comment]
Works THX
