### ISSUE TITLE
users mentioned with the same name but different servers on a post all appear to be the same exact user

### ISSUE THREAD

**Issue by slrgt** [cheeaun/phanpy#229]
**Describe the bug**
on phanpy.social if you go to this post https://firefish.social/notes/9j60zx24n72eue8s all the @'s look like they're the same user but on any other app they are clearly different accounts being mentioned on the post

**Smartphone (please complete the following information):**
 iPhone 10S ios 16.6
and desktop

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
