### ISSUE TITLE
Very long mentions in notification area are cut off with no indicator showing there is more text when opened

### ISSUE THREAD

**Issue by slrgt** [cheeaun/phanpy#230]
If you receive a long reply and go to the notifications section to read it theres a chance you reply before reading the full post because the posts are cur off with no indication that there is more text to be read. Maybe adding a ... or a "read more" icon/button like on the home feed would be helpful.

Device:
iphone 10S

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
