### ISSUE TITLE
Tapping the "show" button in a notification on macOS Ventura 13.5 + Safari 16.6 on dev.phanpy.social does nothing

### ISSUE THREAD

**Issue by hboon** [cheeaun/phanpy#232]
Should probably open a page?

**Comment by cheeaun** [comment]
@hboon is it a specific type of notification? (mention, star, or boost). When clicked, was the tab in foreground or background? 🙏

**Comment by hboon** [comment]
Mention. Definitely not in the foreground. But actually I thought the tab is closed, is it possible?

**Comment by cheeaun** [comment]
@hboon does this still happening consistently? More details would be needed as push notifications seem more complicated for web (compared to mobile 🫣). Use-cases:

- **Multiple accounts** on a single browser tab
  - You can only have notifications for one account.
  - If you try to set push for another account, it'll go haywire 😂)
- **Multiple browser tabs** of Phanpy
  - Clicking notification will try to pick the "best" tab to open and show notification
- **Multiple browser windows** of Phanpy
  - Clicking notification will try to pick the "best" window to open and show notification
- **Multiple accounts on a multiple browser tabs/windows**
  - You can only have notifications for one account.
  - Clicking notification will try to pick the "best" tab/window to open and show notification
  - But the notification doesn't know which tab belongs to which account, so it can open on a tab of a different account. The UI will show it's a notification from another account.
- **Browser-version or PWA-version** of Phanpy
  - I have no idea what will happen 😂
  - It's possible to have multiple PWAs of Phanpy installed too. Notification should be tied to specific PWA installation.
  - Separate PWA installations *can* have different accounts, so it'll work as it's still 1-account → 1-PWA
- Browser/PWA is **not open at all**
  - Clicking notification will open a new browser/PWA window and show notification

**Comment by hboon** [comment]
Sorry, been away. I just received an entry in the Notifications screen for someone whose posts I'm subscribing to (what's the right Mastodon terminology for that?), but no notifications pop up. Should those show up? I have a tab on in Safari with the URL https://dev.phanpy.social/#/ and Safari wasn't active.

I think I had a follow and reply within an hour earlier and there was no notification either.

About the use-cases:

I have:

* Safari
* single account. Sometimes multiple tabs open, but not this particular time
* when I first reported it, I thought Phanpy wasn't open at all. Are notifications support to work only when a tab is open? But either way, the notification did appear and clicking on the button didn't seem to do anything :)

**Comment by cheeaun** [comment]
> I just received an entry in the Notifications screen for someone whose posts I'm subscribing to (what's the right Mastodon terminology for that?), but no notifications pop up.

This should be under "New posts" category.

> Are notifications support to work only when a tab is open?

Should work in the background too, even when browser is closed.

🤔 Maybe can try unsub (uncheck "Allow from xxx") and resubscribe again?

**Comment by hboon** [comment]
Ah, when I visited the Phanpy settings, I see this and I can't click to toggle the checkbox. I tried clicking that log-in link in the screenshot, followed through and still can't check it. I received notifications a week ago when I asked you about it and I was pretty sure I have never seen this checkbox before:

<img width="558" alt="Screenshot 2023-09-12 at 9 10 04 PM" src="https://github.com/cheeaun/phanpy/assets/56189/aff7df16-03d8-45b9-9a05-2931e95c346c">

**Comment by cheeaun** [comment]
@hboon when you click the log-in link and follow through, do you see if the permissions page on your instance include "push"?

**Comment by hboon** [comment]
😭  I can click the checbox now. I didn't do anything in particular. And after I check it, I see this at the top.

<img width="696" alt="Screenshot 2023-09-13 at 6 25 19 PM" src="https://github.com/cheeaun/phanpy/assets/56189/409321a9-7bb3-4fbc-ba4e-a2d777cb4fa1">

Checking my Settings under Safari, Websites tab, I don't see dev.phanpy.social listed under Notifications, but it's listed under Pop-up Windows as "Block and Notify".

**Comment by hboon** [comment]
It doesn't save though. Ah, I get it, I have to go to Notifications and enable "Allow websites to ask for permissions to send notifications" and then come back to that screenshot above, check and it saves.

But why was I receiving notifications previously?

**Comment by cheeaun** [comment]
@hboon hmm interesting. Got to say, Safari's push notifications are even more "bland" than Mobile Safari's, where it shows Safari's own icon instead of Phanpy's icon (maybe because it's not a PWA, and maybe need Sonoma's Safari to add it as PWA). The only hint is the "from dev.phanpy.social" text below the title text in the notification 👀

Will keep this open to see if "Show" button is still working 🤞

**Comment by hboon** [comment]
@cheeaun have verified since the actions in my last message that I can receive notifications. I kept a few of them around and clicked on the show button (actually clicking on the entire notification window works too) to verify it works for these cases:

A. Safari hidden by cmd+h — Safari opens up the right tab if necessary, opens a new window with a single tab if there isn't one
B. Tab is open but not active — switches to the tab
C. Not open in any tab — opens a new window and tab automatically
