### ISSUE TITLE
[Feature request] Add support for private notes on profiles

### ISSUE THREAD

**Issue by Yamakyu** [cheeaun/phanpy#233]
Greetings 

I'ld like to open this feature request by reiterating just how much I love to use Phanpy. Believe me I have tried many Mastodon clients (on web and Android) and have had trouble finding my favs. Phanpy was an instant favorite when I was told about it. The continuous effort for the development of this is amazing client for us to use is greatly appreciated.

I do have one major gripe with Phanpy however, and that's the fact it does not support **private notes** (yet). Private notes is one of my favorite feature of Mastodon, it is immensely practical for me who follow many artists to quickly note if their content is safe to be viewed in a crowded environment or not (NSFW), if I followed them for a specific reason, things like that. Phanpy is an amazing client, and especially for viewing art boosted by others (carousel view, my luv), but it fails at letting me quickly add notes on a user profile I discover organically.

Typically, as of now, when I want to add a note to a profile I either open the official web client or Fedilab, because I can't do it on Phanpy.

It would be amazing to see this feature be supported on Phanpy ✨

Here's how private notes look : 

* [on the official client](https://github.com/cheeaun/phanpy/assets/43894102/48f42533-9535-4a95-bf36-cd6662579156)
* [on Statuzer](https://github.com/cheeaun/phanpy/assets/43894102/b14ffcf7-78d7-4689-a6cf-d5dec6bdcfae), a web client
* [on Fedilab](https://github.com/cheeaun/phanpy/assets/43894102/c5c0b92d-ded8-430e-81d5-eeac065469ce), an Android client

Phanpy does not seem to support yet the display and edit of private notes 

![image](https://github.com/cheeaun/phanpy/assets/43894102/581bdb53-b584-4a5f-b51f-ac87e111d3f8)

That is all ! Thanks again for letting us use such a great client, and I wish you a good day 👋🏿

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
