### ISSUE TITLE
Can't type in replies textbox

### ISSUE THREAD

**Issue by hboon** [cheeaun/phanpy#237]
Click to reply and then clicking in the textbox don't let me type in it:

<img width="1072" alt="Screenshot 2023-09-15 at 10 03 53 AM" src="https://github.com/cheeaun/phanpy/assets/56189/65a2be99-fdaa-41e0-be0b-b1e70acc005e">

Click the pop out button at the top right makes it editable:

<img width="1072" alt="Screenshot 2023-09-15 at 10 03 58 AM" src="https://github.com/cheeaun/phanpy/assets/56189/3f758f62-3fe9-430a-9c08-a9ca0d76e977">

Reproducible on macOS Safari and mobile Safari

**Comment by cheeaun** [comment]
@dr41d45 may need to know more info here 🙏:

- What's the iPhone/iPad model
- What's the iOS/ipadOS version
- What's the browser used

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
