### ISSUE TITLE
[Feature request] Allow users to preview public posts of a specific site without logging in.

### ISSUE THREAD

**Issue by KyoSakuyo** [cheeaun/phanpy#238]
Allow users to preview public posts of a specific site without logging in.

In Elk, We can config this by setting `defaultServer` in elk/nuxt.config.ts. 
![图片](https://github.com/cheeaun/phanpy/assets/59904064/6655d6f7-9750-4af8-b6a3-40704b6de9f2)

**Comment by cheeaun** [comment]
It's already possible to do this, but not shown or linked by default from the home page e.g. https://phanpy.social/#/m.webtoo.ls/p/l

**Comment by KyoSakuyo** [comment]
I see, thx
