### ISSUE TITLE
Follow button is disabled on profile pages

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#240]
Phanpy dev

1. Visit any profile page of user that you are not following

Follow button will be in disabled state
<img width="723" alt="Screenshot 2023-09-16 at 01 57 16" src="https://github.com/cheeaun/phanpy/assets/1143226/16ed7cfb-45ed-4ab9-b121-b8ad52c3c77c">

```html
<button type="button" data-swap-state="" disabled="">Follow</button>
```

**Comment by Fastidious** [comment]
Can’t replicate this on my own install, using latest commit.

**Comment by Alex0007** [comment]
@Fastidious 

Attaching video

https://github.com/cheeaun/phanpy/assets/1143226/58fac5eb-196e-49bd-b387-d75b4ec8fd62

**Comment by Fastidious** [comment]
What OS/browser are you using? I can't repro on macOS' Safari either.

**Comment by Alex0007** [comment]
@Fastidious you are attaching screenshot of user's card, not his profile page

**Comment by Fastidious** [comment]
> @Fastidious you are attaching screenshot of user's card, not his profile page

Aha! I stand corrected, indeed. I can replicate now.

**Comment by Alex0007** [comment]
Thanks for fix!
