### ISSUE TITLE
Interactions graph performance issue

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#241]
Phanpy Dev
Google Pixel 6
Web App

1. Open user profile card (you should not be following this user)

You will observe lags when this element appears (installed web app issues are more noticeable, comparing to when checking in Google Chrome). It might be related to double animation, not sure (block appears + chart is being animated at the same time)

![IMG_20230916_081259_313.jpg](https://github.com/cheeaun/phanpy/assets/1143226/73becd6b-3f38-4c74-8206-543cb76be5be)

https://github.com/cheeaun/phanpy/assets/1143226/eac64a75-f898-43c9-8289-e4965f981f48

**Comment by cheeaun** [comment]
This is kinda expected unfortunately. `height` and `background-position` animations are not hardware-accelerated in (mobile) browsers.

**Comment by Alex0007** [comment]
@cheeaun let me also note that card changing it's height because of animation of block appearing can produce miss-clicks (for example you're trying to click "followers" and suddenly that block appears and moves everything

**Comment by Alex0007** [comment]
Not a problem since it's hidden behind button press
