### ISSUE TITLE
Disable browser input suggestions in search field

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#243]
They are conflicting with UI suggestions

<img width="663" alt="Screenshot 2023-09-21 at 22 42 05" src="https://github.com/cheeaun/phanpy/assets/1143226/a41eb1dc-6a02-4ec9-8aa8-77bc3ad082e1">

[moved second question into separate issue]

**Comment by cheeaun** [comment]
For the 2nd feature, is it possible to open another issue? I'm aware of this following-states feature especially when displaying a list of accounts (for other sheets/pages too, not just on this Search page 🙃) 🙏

**Comment by Alex0007** [comment]
I haven't seen related commit, but it seems like it is fixed now
