### ISSUE TITLE
Incomplete appearance of persian toots in timeline

### ISSUE THREAD

**Issue by RZHSSNZDH** [cheeaun/phanpy#247]
**Describe the bug**
Persian toots are be showed incomplete (in `Read more` method) "even short toots".
- Which site: phanpy.social
- Which instance: mas.to

**Expected behavior**
Phanpy should show the entire toot for short toots and a rather longer part of long toots.

**Screenshots**
![phanpy](https://github.com/cheeaun/phanpy/assets/69734726/0622ea6e-0ac2-48c4-9310-06fe39f71ddd)

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser Firefox
 - Version 118

**Smartphone (please complete the following information):**
 - Device: Galaxy J7
 - OS: lineageOS 17.1 (android 10 based)
 - Browser Fennec
 - Version 117.1

**Additional context**
This issue is related to https://github.com/cheeaun/phanpy/commit/d5a3b48#commitcomment-128927109.

**Comment by RZHSSNZDH** [comment]
It seems the problem is solved:
![image](https://github.com/cheeaun/phanpy/assets/69734726/3f432e97-d365-4d31-a755-6fe5e2fe5e3e)

**Comment by cheeaun** [comment]
@RZHSSNZDH nice, will mark this fixed. If this happens again, feel free to comment or create another issue 🙏
