### ISSUE TITLE
Image caption alignment bug

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#249]
<img width="674" alt="Screenshot 2023-10-03 at 11 20 37" src="https://github.com/cheeaun/phanpy/assets/1143226/774c0ce4-8456-4333-bd5d-7343759b6e8e">

When image is small, caption appears in wrong place

Dev phanpy example: https://dev.phanpy.social/#/mstdn.social/s/111169846056259450

**Comment by cheeaun** [comment]
This is intended. It'll appear on the right side if there's enough space.
