### ISSUE TITLE
Favicon with white background

### ISSUE THREAD

**Issue by danielgarciagarcia** [cheeaun/phanpy#25]
Using Firefox 108.0.1 on Arch Linux, the website's favicon shows up in the bookmark with a white background.

![image](https://user-images.githubusercontent.com/2284360/209343651-1bd31348-6de5-4062-89ce-4f9a6a35be7d.png)

**Comment by cheeaun** [comment]
Hmm.. seems related: https://bugzilla.mozilla.org/show_bug.cgi?id=1701939

But I guess, I'll try `.ico` instead of `.svg` 🤔

**Comment by cheeaun** [comment]
<img width="248" alt="Screenshot 2023-01-24 at 4 34 48 PM" src="https://user-images.githubusercontent.com/2296/214245497-01d16eb7-984f-4249-82bc-b2134bc7b1c0.png">

Changed to new design, used .ico format.

Closing this.
