### ISSUE TITLE
Add the "last 20 posts" plot for every user (including myself!)

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#256]
I love this new graph that appears below some profiles:

![image](https://github.com/cheeaun/phanpy/assets/8617595/a4ec29a9-5c5f-4c0a-a0ca-0da1f3e8ef1e)

I don't see it documented but is this only shown for users I don't follow? While it's useful to decide if I want to follow a someone new, it would also be super useful to see it on users I follow to see if I want to continue following them and even on my own profile to check my posting/boosting habits.

**Comment by cheeaun** [comment]
This should be now up on production.
