### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by jalmeroth** [cheeaun/phanpy#257]
**Describe the bug**
I am unable to build phanpy from source by dowloading an artifact (tar/zip) from [tags](https://github.com/cheeaun/phanpy/tags).

**To Reproduce**
1. Go to https://github.com/cheeaun/phanpy/tags
2. Click on any `tar.gz` link
3. Unpack the downloaded file
4. Change into `phanpy-$version` folder
5. Try to `npm install`, `npm run build`

**Expected behavior**
You get a clean, distributable version of phanpy as described in [Self Hosting](https://github.com/cheeaun/phanpy#self-hosting)

**Error message**
```sh
$ npm run build

> phanpy@0.1.0 build
> vite build

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
failed to load config from /tmp/tmp.bxIPUvnwZt/phanpy-2023.10.07.9b1800d/vite.config.js
error during build:
Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at file:///tmp/tmp.bxIPUvnwZt/phanpy-2023.10.07.9b1800d/vite.config.js.timestamp-1696719649450-96852b13653e5.mjs:19:18
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by cheeaun** [comment]
Tags now have Releases. It's pre-built, without the need to run `npm run build` on your end. Let me know if this works

**Comment by jalmeroth** [comment]
Perfect! That's even better then buildung it myself. Thank you! :+1:

**Comment by jalmeroth** [comment]
Ah, one remark: would it be possible to ship a `.tar` or `.tar.gz` additionally/exclusively?
This would streamline my Dockerfile since `nginx` comes with `curl` and `tar`, but not with `unzip`.

Thanks for considering!

**Comment by jalmeroth** [comment]
Awesome @cheeaun, thank you!

```
FROM docker.io/library/nginx:latest
WORKDIR /usr/share/nginx/html
RUN \
curl -sSOL https://github.com/cheeaun/phanpy/releases/latest/download/phanpy-dist.tar.gz \
&& tar -xf phanpy-dist.tar.gz \
&& rm phanpy-dist.tar.gz
```
