### ISSUE TITLE
[Feature Request/BUG] Add a separate Follow request page to the nav-menu of Phanpy

### ISSUE THREAD

**Issue by KyoSakuyo** [cheeaun/phanpy#258]
![image](https://github.com/cheeaun/phanpy/assets/59904064/92eaf7d3-d7f2-4887-b384-0b6101334990)

Enafore has a separate page in Instance Settings to display Follow requests.

I think a similar page can also be added to the nav-menu of Phanpy, instead of only being able to view Follow requests in Notifications (because Gotosocial has a bug where it sometimes cannot handle Follow requests in Notifications).

**Comment by cheeaun** [comment]
@KyoSakuyo currently the Notifications page on Phanpy exclude follow requests (the API). It has a _separate_ section on the _same_ page, that specifically fetch follow requests API. So even though it's not on a separate page, it should work as if it's on a separate page.

I personally don't understand the point of a full-page UI for follow requests (yet). Now it shows on Phanpy's Notifications page, separately as a top (small) section, scrollable if the list is long. It's not part of the list of notifications so the follow requests won't be "pushed down" by other notifications.

> because Gotosocial has a bug where it sometimes cannot handle Follow requests in Notifications

I'm curious about this, and if this is happening on Phanpy?

**Comment by KyoSakuyo** [comment]
![动画](https://github.com/cheeaun/phanpy/assets/59904064/dc43874f-6cb6-4e87-869f-2d3dfd855209)
>I'm curious about this, and if this is happening on Phanpy?

It did happened!

This is a very annoying bug that has been bothering me for quite some time.

This bug often occurs on my gotosocial instance. However, it does not appear on my mastodon instance (also using phanpy).

The development team of gotosocial progresses relatively slowly, and I guess they are not willing to fix this bug. So I think adding a separate "follow-requests" page on phanpy would be a compromise solution.

**Comment by KyoSakuyo** [comment]
By the way, I can handle follow-requests form *https://enafore.social/requests* and Tusky's Follow-request sidebar normally.

**Comment by cheeaun** [comment]
@KyoSakuyo you found a few bugs 🫣 but let me focus on this one: Follow Requests section should appear above Notifications page. It *should* be working as it's the exact same API call as the `/requests` page on Enafore (and possibly all other clients too). Weird thing is that if you can see the '[New] Follow requests' button at the bottom of Notifications _popup_, means the API is working, but somehow fails on the Notifications _page_ 🤔🤔🤔

It should look like this:

![Screenshot 2023-10-09 at 7 51 02 PM](https://github.com/cheeaun/phanpy/assets/2296/3266108d-c8d8-4756-9530-9bcaf5cd39af)

This will be a little difficult for me to fix as I don't have a GoToSocial instance for testing. 2 possible ways to solve this:

1. Could I get a test account somewhere? (Probably only possible if you're the admin of the instance)
2. Open the browser console and look if there's an error or something unexpected occured (May need debugging skills)

Protip: you can enable Cloak mode in Settings next time before taking screenshot or screen recording. It will hide texts with square boxes 👍

**Comment by KyoSakuyo** [comment]
It works~~
