### ISSUE TITLE
Scrolling to the end of the notifications pop-over closes it

### ISSUE THREAD

**Issue by fasterthanlime** [cheeaun/phanpy#271]
**Describe the bug**

On phanpy.social, opening the "notifications" pop-over, scrolling to the very bottom and then scrolling again, ends up closing the pop-over.

**To Reproduce**

1. Go to phanpy.social
2. Click on the bell icon on the top-right
3. Scroll down to the bottom of the pop-over
4. The pop-over closes (instead of refreshing maybe?)

**Expected behavior**

I don't think it should close, if it's not gonna load more notifications then it should just get stuck at the bottom.

**Screenshots**

https://github.com/cheeaun/phanpy/assets/7998310/0169797e-c992-46c6-8aa5-d31e206c8561

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 17.0 (19616.1.27.211.1)

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
