### ISSUE TITLE
Lookup accounts not working

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#273]
1. Paste fediverse account URL to search input
2. Press Lookup
3. Error is shown

https://github.com/cheeaun/phanpy/assets/1143226/2601bcd9-69e4-4015-83b8-f5b8285dde9d

**Comment by cheeaun** [comment]
You're right. Account lookup doesn't work yet, it'll only work for post URLs. For this case, it's better that you press 'Enter' without 'Look up' which will do a normal search instead.

I know the term 'Look up' is a bit technical and may be confusing; it tries to convert the instance URL into a Phanpy URL, without doing a search on your local instance. For post URLs, it's quite straightforward as the post IDs are already in the URL, but for account URLs, there's no account ID, so it still need another request to get the ID first 😓.

**Comment by Alex0007** [comment]
I guess it's now working
