### ISSUE TITLE
Can't open post creation popup on Pleroma

### ISSUE THREAD

**Issue by Xen4n** [cheeaun/phanpy#275]
When I tap on the feather button on account in Pleroma instance, client blocks - there are no actions works anymore. Only page refresh returns client workability.

- Which site: phanpy.social
- Which instance: social.net.ua
- Which device: Android (Samsung Internet) and Web (Google Chrome)

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
