### ISSUE TITLE
Bigger post textarea

### ISSUE THREAD

**Issue by Fastidious** [cheeaun/phanpy#28]
Would it be possible adding a handful of rows to the post textarea? I have noticed it is rather too small now (only two rows).

**Comment by Fastidious** [comment]
I forgot to specify I see this ion iOS Safari.

**Comment by cheeaun** [comment]
@Fastidious you can try out typing more lines of text, it's auto-grows.

**Comment by Fastidious** [comment]
@cheeaun ahh, so it does! That’s pretty nifty. Closing this issue, and thank you very much for the fast reply!
