### ISSUE TITLE
Alt text bottom panel does not respond to Esc

### ISSUE THREAD

**Issue by forteller** [cheeaun/phanpy#281]
**Describe the bug**

Pressing Esc does not close the panel showing the alt text of an image

**To Reproduce**
1. Click on the Alt indicator on an image
2. Press Esc –> Nothing happens

**Expected behavior**
Panel should close

**Desktop (please complete the following information):**
 - OS: Nobara Linux
 - Browser Firefox
 - Version 118

Thank you for your work!

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
