### ISSUE TITLE
Please close only one panel at a time when pressing Esc

### ISSUE THREAD

**Issue by forteller** [cheeaun/phanpy#282]
**Describe the bug**
I noticed that when pressing Esc in the situation described in #69 both the author panel and the right panel disappears at the same time. 

For me I think the most intuitive thing would be to only close the most recently opened panel each time you hit Esc, so that first it closes the author panel and then you hit it again to close the right panel. If not you might open the author panel to check out the author of one toot, then intend to go back to reading the rest of the thread, but lose your place in the thread when you hit Esc and both the author panel and the right panel disappears at the same time.

**To Reproduce**
1. Click on a toot to open the right panel
2. Click on the author to open the author panel
3. Press Esc

**Expected behavior**
Only closes the "top" panel (the last one opened)

**Desktop (please complete the following information):**
 - OS: Nobara Linux
 - Browser Firefox
 - Version 118
 
Thanks again! :)

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
