### ISSUE TITLE
notifications page broken by null status

### ISSUE THREAD

**Issue by felix9** [cheeaun/phanpy#288]
on phanpy.social and dev.phanpy.social, my notifications page throws an error and becomes unresponsive:
```
notification.jsx:282 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at notification.jsx:282:58
```

It's trying to render "Y liked 4 of your posts", and `_statuses` is an array of 4 elements, where the 3rd element is null.

The null seems to be actual data returned from the server. On mastodon.social, my notifications has three entries "Y favorited your post" with no post shown. I'm not sure how that happened, but this looks to me like a bug on the server, producing unexpected data, that causes phanpy to fail.

**Comment by cheeaun** [comment]
@felix9 thanks! Is it possible to get the JSON response output from the API? If this is not possible, I'll be fixing this in the blind, assuming that one of the notification item has `null` status — possibly an user liked a deleted post or the server really produced unexpected response.

**Comment by felix9** [comment]
this is one of the bad entries from the XHR. tell me if you want more context
```json
    {
        "id": "210692307",
        "type": "favourite",
        "created_at": "2023-10-28T16:08:09.723Z",
        "account": {
           /* ... */
        },
        "status": null
    }
```

**Comment by cheeaun** [comment]
@felix9 thanks! Just wondering, does this show up on the official web UI/apps (or other apps)?

**Comment by felix9** [comment]
on the mastodon.social web UI, this shows up as "Y favorited your post", but without a post shown.

I think there's not really much point in showing that to the user, other than maybe it's good to have the bug visible rather than invisible

**Comment by cheeaun** [comment]
@felix9 I've added a potential fix https://github.com/cheeaun/phanpy/commit/146e5d1a7e75fe964346cc203cdfa3e44f325603 on dev site, can you try it out? Thanks 🙇‍♂️

**Comment by felix9** [comment]
yup, fixed on dev site. thanks!
