### ISSUE TITLE
Hashtag page doesn't show any posts or the "Follow" option when using GoToSocial

### ISSUE THREAD

**Issue by filipesmedeiros** [cheeaun/phanpy#294]
**Describe the bug**
In my (personal) instance, the hashtag page seems to have two bugs. At https://mastodon.social/@cheeaun/111336065434816529, Chee asked me to report them here:

1. ~~The "Follow" option in the top right menu doesn't exist (not even disabled). There is a picture attached to show this.~~ See below why this is not a bug! :)
2. The page can't load the posts with the tag.

- Which site: phanpy.social
- Which instance: social.filipesm.eu
- Which fedi software: GoToSocial

**To Reproduce**
1. Run a GTS server
2. Connect to it using https://phanpy.social
3. Search for a hashtag (_e.g._ #DoughnutEconomics)
4. Go to the hashtag page and see the bug

**Expected behavior**
The "Follow" button exists and posts show up.

**Screenshots**
<img width="1043" src="https://github.com/cheeaun/phanpy/assets/26208850/f84ca6b4-8cd3-4f92-9073-880fa2ecb1bd">

**Desktop (please complete the following information):**
 - OS: MacOS 14.2 Ventura
 - Browser: Vivaldi
 - Version: 6.2

**Additional context**
I believe that bug number 2 (posts not showing up) is not a bug of Phanpy, but it's just the way GTS works: I have no access to other server's posts if I'm not federating with them, and there isn't backfilling of old posts also.

While researching for this report, I noticed that the above is not true. It might actually be because the request has no authentication, and so we get a ```401``` back. Picture below.

<img width="879" alt="Screenshot 2023-11-01 at 17 34 22" src="https://github.com/cheeaun/phanpy/assets/26208850/366c8e18-9f06-41b4-8386-0c27c1f88c94">

**Comment by filipesmedeiros** [comment]
Indeed it seems to be that, because for some reason, if I click a hashtag on my home page, it takes me to a correct page where I have the posts there (still no "Follow" button though). And that request is indeed authenticated with an "Authorization" header.

**Comment by filipesmedeiros** [comment]
Apparently, according to [this file](https://github.com/cheeaun/phanpy/blob/main/src/pages/hashtag.jsx), we only display the "Follow" button if the ```tags``` request is successful, and [GTS doesn't implement it](https://docs.gotosocial.org/en/latest/api/swagger/) for some reason. What do you think we could do?

**Comment by cheeaun** [comment]
@filipesmedeiros perhaps would be great if this is reported to GTS 🤔 From their [roadmap](https://github.com/superseriousbusiness/gotosocial/blob/main/ROADMAP.md), seems that they've implemented hashtag federation since [July](https://github.com/superseriousbusiness/gotosocial/pull/2032) and marked as done. Not really sure if it includes following/unfollowing besides just viewing.

You're right regarding the `tags` request, it's used to know if user is following the tag or not. And… via same endpoint, `POST /api/v1/tags/:id/follow` ([doc](https://docs.joinmastodon.org/methods/tags/#follow)) is needed to follow the hashtag.

**Comment by filipesmedeiros** [comment]
@cheeaun I've reported it and it's on the backlog! https://github.com/superseriousbusiness/gotosocial/issues/2326#issuecomment-1789479611 They have implemented tag timelines but not the Tags endpoints :)

But the other issue with fetching the timeline is still there, correct?

**Comment by cheeaun** [comment]
@filipesmedeiros this is a little difficult for me to test without an account 😬 Few things to check:

- CORS headers?
- Strict origin issues? But other non-hashtag-page requests works right? 🤔
- Really weird that `Authorization` header is gone. Other requests have them?

Thanks! 🙇‍♂️

**Comment by filipesmedeiros** [comment]
@cheeaun I will debug this tomorrow :)

**Comment by filipesmedeiros** [comment]
@cheeaun I ran this locally and it's actually fixed in ```dev``` so... I'm gonna maybe wait for you to merge it into ```main``` and then we can close this? Or maybe close it already.
