### ISSUE TITLE
Play on video removes content from the page

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#296]
Phanpy dev

1. Go to [this post with video](https://dev.phanpy.social/#/mastodon.social/s/111336534954075309)
2. Click play
3. All content disappears (no errors in console or anything useful)

Can reproduce **only** in Arc Browser

https://github.com/cheeaun/phanpy/assets/1143226/98e4f113-8f0f-4b33-810d-7499035e16ac

**Comment by Alex0007** [comment]
Closing because issue is reproducible only in 1 browser. I guess there is some problem with browser

**Comment by cheeaun** [comment]
Hey thanks, I'm also able to reproduce this on Arc browser. Seems specific to HDR videos, as I try other (non-HDR) videos and they seem to work.

I know that Chrome had (or still having) issues with HDR videos that would hang the whole page. I didn't really go further and investigate or report any bugs to them.
