### ISSUE TITLE
Filters are not applied to shortcuts

### ISSUE THREAD

**Issue by eliocamp** [cheeaun/phanpy#299]
**Describe the bug**

Custom filters are applied to the main timeline but don't seem to apply to shortcuts (at least the hashtag shortcut).

**To Reproduce**
1. Create a hashtag shortcut
2. Create a new filter that should apply to a recent post 
3. Reload the page
4. The post still appears without filter

**Expected behavior**

Filters should apply to hashtag shortcuts (like in mastodon's advanced view).

**Comment by cheeaun** [comment]
Should be fixed now in prod 🙇‍♂️
