### ISSUE TITLE
Instance emotes not always displaying correctly in profile name

### ISSUE THREAD

**Issue by Gyoo** [cheeaun/phanpy#301]
**Describe the bug**
- Which site: phanpy.social
- Which instance: My account is on shelter.moe, bug seen on account from misskey.io

**To Reproduce**
Go to any account with custom emojis in their profile name

**Expected behavior**
All emojis should be displayed the same way as they are on their instance

**Screenshots**
Profile as seen on Phanpy
![aI7fAYW](https://github.com/cheeaun/phanpy/assets/3592205/0d89e687-d5f0-4ce9-ad09-a3e2a5b733d6)

Same profile as seen on Misskey
![image](https://github.com/cheeaun/phanpy/assets/3592205/f9622585-26c5-4b1f-80d7-f9d8ab7de47d)

**Desktop (please complete the following information):**
 - OS: W11
 - Browser: Firefox
 - Version: 119.0

**Comment by cheeaun** [comment]
Seems like Mastodon can't "find" the image for that custom emoji 🤔 (the API response doesn't include it). If you view it on your instance, it also doesn't show that emoji https://shelter.moe/@MatchaNear@misskey.io

**Comment by Gyoo** [comment]
Nice catch, I didn't try to check this user's profile from my instance. Not sure there's anything you can do in that case...

**Comment by cheeaun** [comment]
@Gyoo yeah, there's not much can be done if the API doesn't return the emoji 😬
