### ISSUE TITLE
[Feature] Link/profile verification

### ISSUE THREAD

**Issue by filipesmedeiros** [cheeaun/phanpy#316]
**Describe the feature**
Profile/link verification where people can increase trust that their profile is real and not an impersonation, by highlighting a link on their profile. Similar to what Mastodon's UI does.

**Additional context**
This seems relatively easy (we can even copy the scraping logic from Mastodon?), so I can try to create a PR for that and the maintainer @cheeaun can create the UI however he sees fit? :)

**Comment by forteller** [comment]
This is already implemented with a green checkmark if they've verified their website.

![image](https://github.com/cheeaun/phanpy/assets/343561/b412ed70-63c9-4bab-a9e4-9039c63b512b)

**Comment by filipesmedeiros** [comment]
@forteller huh, is the process the same? I can't seem to get my profile verified, and for example:

This is on my instance's UI
![image](https://github.com/cheeaun/phanpy/assets/26208850/b80b5909-053c-4d04-8d00-20d49367e58b)

This is one the original profile:
![image](https://github.com/cheeaun/phanpy/assets/26208850/b643c07a-c7b6-49d3-acd5-f8228842de64)

Might be related to me being on GoToSocial? Seem unlikely given this should be a frontend thing, but who knows?

**Comment by filipesmedeiros** [comment]
I just checked the logs on the browser and it is indeed a backend thing, so I'll file this with GoToSocial! Thanks for the help :)

**Comment by cheeaun** [comment]
@filipesmedeiros I'm not sure if GTS implemented verified links (you could check their issues).

But from my understanding, verified links are not federated. *Every* instance need to verify the links on their own.

**Comment by filipesmedeiros** [comment]
@cheeaun on the Mastodon UI, in my (old) instance, mastodon.green, you can see links that are verified in profiles from different instances. So there is some sort of federation/trust going on, right?
