### ISSUE TITLE
Once the boost confirmation dialog is opened in the post details, other UIs such as Like will no longer respond to clicks.

### ISSUE THREAD

**Issue by nibushibu** [cheeaun/phanpy#332]
**Describe the bug**
Once the boost confirmation dialog is opened in the post details, other UIs such as Like will no longer respond to clicks.
- Which site: dev.phanpy.social AND  phanpy.social
- Which instance: social.vivaldi.net

**To Reproduce**
1. Go to some post detail
2. Click on Boost 🚀
3. Close boost confirm dialog
4. Clink Like ♥️ (you can't click Like)

**Smartphone (please complete the following information):**
 - Device: Pixel 7a
 - OS: Android 14
 - Browser: Vivaldi
 - Version: 6.2.3110.143

**Comment by cheeaun** [comment]
Should be fixed now on production 🙏

**Comment by nibushibu** [comment]
@cheeaun Wow! Thank you for the insanely quick fix!
