### ISSUE TITLE
text getting clipped in profile description from non mastodon users

### ISSUE THREAD

**Issue by wakest** [cheeaun/phanpy#379]
heres a friendica account https://libranet.de/profile/wakest
<img width="331" alt="image" src="https://github.com/cheeaun/phanpy/assets/7890201/e27dcc40-39c0-4a35-bd14-02418ab568d9">

and a micro.blog account https://manton.org/activitypub/manton
<img width="606" alt="image" src="https://github.com/cheeaun/phanpy/assets/7890201/608e5bb3-f51e-4803-8711-245a58899da9">

am viewing these from my mastodon account via https://dev.phanpy.social/

**Comment by cheeaun** [comment]
@wakest what's your OS + browser + versions? 🙇‍♂️

**Comment by wakest** [comment]
looks like you also fixed this! I am on latest Firefox on macOS 13.6.1

**Comment by wakest** [comment]
hey @cheeaun I am noticing this in a new place now, not sure if its the same issue or not but: 
<img width="434" alt="image" src="https://github.com/user-attachments/assets/85708382-2034-4039-a686-c9394e6c8f86">
