### ISSUE TITLE
Duplicate Lemmy self-referential "quote posts"

### ISSUE THREAD

**Issue by cheeaun** [cheeaun/phanpy#385]
> this is apparently not fixed 
> <img width="676" alt="image" src="https://github.com/cheeaun/phanpy/assets/7890201/884a23b4-c956-4ad1-bbd5-fae7ff171bc6">
> 
> just came across this issue on this lemmy post https://lemmy.ml/post/9736352 while logged into https://dev.phanpy.social/#/social.wake.st/
> 
> (we should also probably rename this issue "Phanpy is confused by posts from Lemmy" for later searchability )

_Originally posted by @wakest in https://github.com/cheeaun/phanpy/issues/140#issuecomment-1875363447_

**Comment by cheeaun** [comment]
For some reason, I can't reproduce this on my side. I'll try investigate.

**Comment by wakest** [comment]
was using the newest Firefox on macOS if that helps

**Comment by wakest** [comment]
I just checked and this link is not showing the issue anymore! did you end up fixing this @cheeaun?

**Comment by cheeaun** [comment]
@wakest I did some potential fixes, but can't confirm since I can't reproduce this on my side 🙈

**Comment by wakest** [comment]
I follow a bunch of lemmy accounts and have not noticed this so it seems like you fixed it. this issue could probably be marked as fixed :)
