### ISSUE TITLE
Photo scroll focus issue

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#40]
Photo in feed starts scrolling after preview is opened. And it can't be focused on mobile (to start scrolling) in any way (only click that opens preview)

Example: https://youtube.com/shorts/cC1nkFHr9I8?feature=share

**Comment by cheeaun** [comment]
Attempted to fix this via https://github.com/cheeaun/phanpy/commit/e4d9e7f7db19be406aaebf2e012154a7814e5784

Probably can check it out if this bug is still happening for you 🙇‍♂️
