### ISSUE TITLE
columns fail to load when adding trending

### ISSUE THREAD

**Issue by teddyber** [cheeaun/phanpy#426]
**Describe the bug**
adding a trending column (local instance or a remote one) fails

**To Reproduce**
I have 5 columns (following, list #1, list #2, remote timeline, notifications)
adding a trending column fails, cannot close the shortcuts pane
(adding a local timeline works fine)
reloading the page fails as well, some columns never load, settings are unavailable
had to manually edit localStorage to remove trending column and reload and this made phanpy functional again

**Expected behavior**
a new column with trending topics

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser firefox 122
 - Version both phanpy.social and dev.phanpy.social

**Comment by cheeaun** [comment]
@teddyber is it possible to attach a screenshot of the columns? I'm unable to reproduce this on my side (Firefox 123, macOS), so will need more details, e.g. what's the instance you're on or at least the software your instance is on (Mastodon or other fediverse software + version number) 🙏

**Comment by teddyber** [comment]
it works now 🤷‍♂️
