### ISSUE TITLE
Bookmark link with instance and username

### ISSUE THREAD

**Issue by jneubert** [cheeaun/phanpy#436]
I don't want to save login information in the browser, and I clean cookies regularly. Every time, when I open phanpy, I have to type the instance name and my username, again and again. A URL to a login form where I have only to supply the password would be a great relief.

If this function already exist, I would be super happy with a hint - I was not able to find something on the web or in the docs.

**Comment by cheeaun** [comment]
@jneubert not sure if this would work for you, try this `https://phanpy.social/#/login?instance=mastodon.social&submit=1`. Replace `mastodon.social` with your instance, it'll auto-redirect you to your instance's login form.

**Comment by jneubert** [comment]
Thanks - that worked fine! Perhaps a hint (on https://github.com/cheeaun/phanpy/blob/main/README.md or elsewhere) could be helpful? 

Thank you for the great tool!
