### ISSUE TITLE
Spoiler not fully covering content in comments section

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#44]
<details>
  <summary>Example</summary>
  
![Screenshot_20230103-181440](https://user-images.githubusercontent.com/1143226/210374679-c07be9b8-d166-4899-b802-979aa65e9119.png)
  
</details>

**Comment by cheeaun** [comment]
I assume this is fixed as this effect is no longer used. Feel free to reopen if you see this bug again.
