### ISSUE TITLE
History back when photo gallery is opened

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#45]
Instead of closing photo preview – (web) app is closing fully

**Comment by LukaszH77** [comment]
That's my main issue while using Phanpy on my phone. The habit of swiping back to go back is too strong for me to remember not to use it in Phanpy so I'm closing the app and opening it back all the time.

**Comment by bmonjoie** [comment]
It's really annoying me too on my phone, especially since when I open Phanpy back, it brings me back to the top of the list.

**Comment by cheeaun** [comment]
Should be working now on production site.

**Comment by bmonjoie** [comment]
Yes, I saw it working yesterday evening! Thank you so much for this. It makes my experience with Phanpy on mobile much more enjoyable!
