### ISSUE TITLE
Please show character counter

### ISSUE THREAD

**Issue by forteller** [cheeaun/phanpy#467]
**Is your feature request related to a problem? Please describe.**
I quite regularly go over my character limit and have to remove chars before posting. How many do I have to remove? Is it even feasible, or is it too many and I should give up and split the post into two post or find another solution? I don't know, because the character counter doesn't give precise information.

I totally understand the allure of a more sleek indicator with just a circle filling up and color codes. I do! But for me, having no idea how many chars I have to remove to be able to post is actually quite annoying, often multiple times every day.

**Describe the solution you'd like**
Either a setting or just by default show an actual char counter – at least when you're over the limit, that's the most important time. Having the number within the circle is probably not good, the text will be very small. An alternative could be that it starts out as the circle, and when you get to 0 chars left it turns from a yellow circle to a red one, just like today. When you get to -1 chars, though, the red circle morphs into a red number that counts the chars you are over the limit. When you get back to 0 chars the number morphs back into a red circle.

This would have the benefit of making it more clear if you are at the limit or above the limit. The fact today that both 0 chars and -X chars are shown as a red circle makes me often uncertain of if I can post or not.

**Additional context**
Thanks as always! Amazing work!

**Comment by cheeaun** [comment]
@forteller are you on Firefox?

**Comment by forteller** [comment]
Yes, on Linux :)

**Comment by forteller** [comment]
That was fast! And very well implemented! Thank you very much!
