### ISSUE TITLE
`j` and `k` keyboard shortcuts not behaving as expected

### ISSUE THREAD

**Issue by mickaobrien** [cheeaun/phanpy#500]
**Describe the bug**
- Which site: dev.phanpy.social
- Which site version: 2024.04.15.57390a2

On `dev.phanpy.social`, pressing:
- `j` triggers the hotkey event twice and the focus moves to the status after next instead of the next one
- `k` toggles cloak mode instead of moving the focus to the previous status

The other keyboard shortcuts seem to be working fine.

I just had a look locally and disabling `useKey` in `useHotKeys` ([code](https://github.com/cheeaun/phanpy/blob/57390a291b20aa268513a40c60954a3bae5237d2/src/utils/useHotkeys.js#L11)) fixes these problems, but I'm not sure what the actual issue is.

**Desktop:**
 - OS: Ubuntu 22.04
 - Browsers: Firefox 124.0.2, Chrome 123.0.6312.105

**Comment by cheeaun** [comment]
@mickaobrien may I know what's the keyboard you're using?

**Comment by wakest** [comment]
just came across this one too on `dev` J/K navigation pretty borked

**Comment by cheeaun** [comment]
@wakest @mickaobrien should be fixed in latest dev now.

**Comment by wakest** [comment]
@cheeaun seems fixed to me too! shall we close the issue?
