### ISSUE TITLE
Vote percentages are broken

### ISSUE THREAD

**Issue by poVoq** [cheeaun/phanpy#510]
When using Phanpy with Akkoma, this is how votes get displayed:

![grafik](https://github.com/cheeaun/phanpy/assets/940360/eee61650-7496-4cc1-bfc1-3416c007744e)

This afaik started to happen a few versions ago, but it might have always been the case.

On the normal akkoma-fe the votes show the correct percentages.

**Comment by cheeaun** [comment]
The `voters_count` returned (it shows "1 voter") is wrong. Seems relevant to this https://akkoma.dev/AkkomaGang/akkoma/issues/190
