### ISSUE TITLE
Crash when clicking compose button

### ISSUE THREAD

**Issue by kkoyung** [cheeaun/phanpy#52]
**Describe the bug**
I logged in my GoToSocial server with Phanpy. When I click the compose button at the right botton corner, the browser popped out the alert message "Failed to load instance configuration. Please try again.". After clicking "OK", the browser reload the web app. Therefore, I cannot create new post.

**To Reproduce**
1. Login an account on a GoToSocial server.
2. Click the compose button at the right-bottom corner.
3. An alert with the message "Failed to load instance configuration. Please try again." popped out.
4. After clicking "OK", the browser reload the web app.

**Expected behavior**
Display the compose dialog to create a new post.

**Investigation**
The alert comes from the following code in `src/components/compose.jsx`:

``` javascript
  const currentAccount = getCurrentAccount();
  const currentAccountInfo = currentAccount.info;

  const configuration = useMemo(() => {
    try {
      const instances = store.local.getJSON('instances');
      const currentInstance = currentAccount.instanceURL.toLowerCase();
      const config = instances[currentInstance].configuration;
      console.log(config);
      return config;
    } catch (e) {
      console.error(e);
      alert('Failed to load instance configuration. Please try again.');
      // Temporary fix for corrupted data
      store.local.del('instances');
      location.reload();
      return {};
    }
  }, []);
```

According to the function `initMasto(params)` in `src/app.jsx`, since GoToSocial uses v1 Mastodon api, the uri `"https://mydomain.com"`, rather than the domain `"mydomain.com"`, is used as the index of a member of `instances`. So, the index of the member in `instances` at line 6 above contains the protocol part.

I found that in the function `onSubmit` in `src/pages/login.jsx`, the the protocol part is always removed from `instanceURL`. This value then becomes the value of `currentAccount.instanceURL`. So, the value of `currentInstance` at line 7 above doesn't contain the protocal part.

Hence, at line 8 above, the configuration cannot be retrieved, and then an error is catched.

**Solution**
I tried to change a line in `initMasto(params)` function in `app.jsx` from
``` javascript
      instances[(domain || uri).toLowerCase()] = info;
```
to
``` javascript
      instances[(domain || uri.replace(/(^\w+:|^)\/\//, '')).toLowerCase()] = info;
```
to make sure no protocol part is including the index of the member of `instances`. It works with my GoToSocial server.

However, I am not sure whether the whole uri was used intentionally for other purposes. So, I simply create an issue, instead of a PR.

**Desktop (please complete the following information):**
 - OS: Arch Linux 6.1.8-arch1-1
 - Browser: Firefox
 - Version: 109.0 (64 bit)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS16.3
 - Browser: Safari
 - Version: 16.3

**GoToSocial Version**
GoToSocial 0.6.0 git-f9e5ec9

**Phanpy version**
Phanpy [git-305bb92](https://github.com/cheeaun/phanpy/commit/305bb92)

**Comment by cheeaun** [comment]
Thanks for the detailed bug report! I assume you're using the dev site, and I've pushed a possible fix, can you try again? 🙏

**Comment by kkoyung** [comment]
I've tested with the newest commit. It works fine for you now.
Thanks for your quick response. I will close this issue.

Reference: the related commit for fixing this bug - [Strip protocol from instance domain/uri ](https://github.com/cheeaun/phanpy/commit/e282f5df2ac7df93551fae8dda316dcfa7ea4994)
