### ISSUE TITLE
Can't delete post because of element overflow

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#527]
**Describe the bug**
Phanpy Dev

You can't remove post from thread because menu don't have "delete post" functionality. This functionality is available only when post is in focus (or something like that). But you can't go to post page because post date (link to post) is behind floating menu thing.

https://github.com/cheeaun/phanpy/assets/1143226/897967bd-aabb-4ddd-a1e8-28afa4522c0b

**Comment by cheeaun** [comment]
It's possible to go to post page by clicking on 'View post by...' menu item in the menu.

**Comment by Alex0007** [comment]
@cheeaun wow, i did not notice it. Should i close?

**Comment by cheeaun** [comment]
@Alex0007 should be closeable 😄 The 'View post' menu probably needs better visibility (or better icon or copy) but honestly this menu is getting crowded as more features are added 😅
