### ISSUE TITLE
Dismiss settings modal when viewing own posts

### ISSUE THREAD

**Issue by zorae** [cheeaun/phanpy#55]
**Describe the bug**
When navigating to my own posts through Settings > Account > Posts, the account modal gets dismissed but the settings modal remains on screen

**To Reproduce**
1. Tap the Settings gear in the top left corner
2. Tap own account name
3. Tap on "Posts"

**Expected behavior**
Both the account modal, as well as the settings modal get automatically dismissed so I can view my posts

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 16.3

**Comment by cheeaun** [comment]
Reopening this as the fix won't be in production site yet.

**Comment by cheeaun** [comment]
Sorry a little late but now on production 🚀
