### ISSUE TITLE
Avatar doesn't show at top left on the main page

### ISSUE THREAD

**Issue by Fastidious** [cheeaun/phanpy#560]
**Describe the bug**
Avatar doesn't show at top left of the main page.

**To Reproduce**
1. Login on a GoToSocial server
2. Notice the missing avatar at the top left of the page.

**Expected behavior**
Avatar should show.

**Screenshots**
![image](https://github.com/cheeaun/phanpy/assets/8352292/4d538c88-1f13-4486-897a-946b40635c2e)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Chrome

**Comment by Fastidious** [comment]
@cheeaun, I have neglected to offer you an account on an instance running GoToSocial. Please let me know if you want/need one.

**Comment by cheeaun** [comment]
@Fastidious is it only 1 account?

**Comment by Fastidious** [comment]
Yes, one account. If I add a second one (Mastodon backend), the avatar shows. If I missed that the avatar shows only when there is more than one account, I will slap myself silly.

**Comment by cheeaun** [comment]
@Fastidious yeah, avatar only shows if more than 1 account added. Don't have to blame yourself, it's a rather hidden logic where I assume the avatar is not useful if there's only 1 account, which I suspect would be common for average users.

**Comment by Fastidious** [comment]
Thank you!
