### ISSUE TITLE
Reboosts scroll arrow buttons don't work with 4 columns layout on Firefox

### ISSUE THREAD

**Issue by scambier** [cheeaun/phanpy#586]
**Describe the bug**

On phanpy.social 2024.06.23.20d0b1c https://hachyderm.io

The right arrow button to horizontally scroll through reboosts stops working after 1 click, when the display uses 4 columns.

**To Reproduce**
1. Use Firefox
2. Set the layout to use 4 columns (e.g. Home, Local, Trending, Notifications)
3. Find a Reboosts section with more than 2 posts
4. Click on the right arrow button
5. The button only works once

**Expected behavior**

The button should work.

**Screenshots**

![image](https://github.com/cheeaun/phanpy/assets/3216752/e63c1c6b-e375-41eb-b191-6ff941fe059a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 127.0.2

**Comment by Squaredude** [comment]
I wonder if it's related to this one: #570 

What is your screen resolution? Are you using any sort of sidebar? Anything that shrinks Firefox or the page from the sides?

**Comment by scambier** [comment]
Ah yes this is the same issue, I'll comment on this one 👍
