### ISSUE TITLE
Click `ESC` to cancel draft toot with image/text is stuck with a flashing dialog

### ISSUE THREAD

**Issue by hboon** [cheeaun/phanpy#59]
1. Click to start composing
2. Type "x" or drag an image file in
3. Click `ESC` and the dialog with "You have unsaved changes. Are you sure you want to discard this post?" appears and disappears quickly

On dev:

The dialog in this screenshot flashes (appears and quickly disappears) if we use `ESC` instead of clicking the `X` button. This screenshot was taken by clicking the `X` button:

<img width="800" alt="Screenshot 2023-02-14 at 9 46 27 AM" src="https://user-images.githubusercontent.com/56189/218617326-273522bb-3762-4d6a-a27b-50601c5e3676.png">

**Comment by cheeaun** [comment]
Seems like you're using Safari. I just tried it on Version 16.3 (18614.4.6.1.5), able to reproduce this bug 🤔

**Comment by cheeaun** [comment]
Should be fixed now on production. Feel free to reopen if the bug is still happening 🙇‍♂️
