### ISSUE TITLE
Corners of selection with keyboard navigation are slightly off

### ISSUE THREAD

**Issue by hboon** [cheeaun/phanpy#60]
Both dev and prod.

<img width="699" alt="Screenshot 2023-02-16 at 11 15 03 AM" src="https://user-images.githubusercontent.com/56189/219259092-547bf0d4-5428-4f0a-a303-fc9f357f240e.png">

**Comment by cheeaun** [comment]
Should be fixed now (not by me) with latest Safari 16.4 👀
