### ISSUE TITLE
wrong color-scheme for language selection tool

### ISSUE THREAD

**Issue by roughnecks** [cheeaun/phanpy#604]
**Describe the bug**
When writing a post, if you click to select the language on dark theme, this appears:
https://i.imgur.com/T6M4t3N.jpeg

- Which site: [self-hosted phanpy]
- Which site version: [2024.07.22.e6e884f]
- Which instance: [e.g. livellosegreto.it]

**Expected behavior**
Colors should match the dark theme, at least a dark background and some light text.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [Versione 126.0.6478.185 (Build ufficiale) (a 64 bit)]

**Comment by roughnecks** [comment]
I built latest production and it's fixed.. not sure how, if you didn't do anything :)

https://i.imgur.com/vTYx433.jpeg

**Comment by cheeaun** [comment]
thanks for closing. it's fixed here https://github.com/cheeaun/phanpy/commit/a1c419b675e4769328d69c4d4f4b674d05cf8397
