### ISSUE TITLE
Notifications dialog cannot be closed on iPad

### ISSUE THREAD

**Issue by FND** [cheeaun/phanpy#606]
**Describe the bug**
On an ~older~ iPad (tested on iOS 16.7.9 and above) in PWA mode only, after opening the _Notifications_ drop-down dialog (via the bell symbol in the upper right), it appears impossible to close the dialog again: Clicking anywhere outside the dialog does nothing, so the only option remains using that dialog's _See all_ or _Mentions_ links to switch to a different view entirely.

- Which site: phanpy.social
- Which site version: 2024.07.22.81e330d
- Which instance: hachyderm.io

**To Reproduce**
1. On an iPad with iOS 16.7.9
1. Add Phanpy to homescreen
1. Open Phanpy from homescreen
1. Go to _Home_
1. Click on 🔔 _Notifications_ to open the corresponding dialog
1. Click anywhere outside to close the dialog, unsuccessfully

**Expected behavior**
Clicks outside the _Notifications_ dialog should not be swallowed, perhaps also close that dialog.

**Screenshots**
<img src="https://github.com/user-attachments/assets/6388f85e-b343-461d-9de2-7401b3d182a4" alt="screenshot of Phanpy on iPad" width="600" />

**Smartphone (please complete the following information):**
 - Device: iPad (5th generation)
 - OS: iOS 16.7.9
 - Browser: Safari (PWA on homescreen)

**Comment by jeffsikes** [comment]
This is also occurring on a newer iPad, latest iOS version. You can get around the issue by clicking the "See all" button.

Only occurs if I have it installed as a PWA. Same behavior does not occur in a regular safari browser window.

**Comment by FND** [comment]
Thanks, Jeff!

FWIW: I had tried debugging this, but it's the kind of issue that seems tricky to investigate without being familiar with the code base. If I'm not mistaken, [React Menu](https://github.com/szhsin/react-menu) is being used for this purpose?

Another observation from the aforementioned older iPad, which might or might not be related: For a lot of interactions it takes a long time until there's any UI feedback (e.g. clicking on a message to open the respective thread, it might take anywhere from 500 ms to several seconds for the modal dialog to show up). The same doesn't seem to happen on other devices.

**Comment by FND** [comment]
It appears the most recent iOS update (16.7.10) fixed the issue; at least I can't reproduce it anymore now. So it looks like this was never a Phanpy issue in the first place - closing this issue in the hope that Jeff will make the same observation.

**Comment by jeffsikes** [comment]
I don't think it was the iOS update, but it's working for me now as well. 

I have PWAs for Phanpy.social and one for my own personal Phanpy site, which was 23 commits behind. I synced the fork today and only after the sync did my personal Phanpy site start working.

Looks like it got fixed here: 🎉 

https://github.com/cheeaun/phanpy/commit/ad7193d0674f8d518d0e24cba0db1e3852352867
