### ISSUE TITLE
[FR] Opening a Mastodon link mentioned in a toot in-place instead of another tab

### ISSUE THREAD

**Issue by hboon** [cheeaun/phanpy#64]
Especially useful if it's linking to a Mastodon instance different from the logged-in user's.

<img width="1099" alt="Screenshot 2023-02-20 at 10 10 01 AM" src="https://user-images.githubusercontent.com/56189/219993207-a5c38188-1102-4fb4-a899-b6626e46a36a.png">

**Comment by cheeaun** [comment]
This is on prod.
