### ISSUE TITLE
Pressing `k` (not `j`) to navigate after <enter> on a post in the timeline focus on the timeline instead of the newly opened thread

### ISSUE THREAD

**Issue by hboon** [cheeaun/phanpy#76]
Reproducible in https://dev.phanpy.social but not https://phanpy.social

1. Navigate with `j`/`k` on timeline to a post that is threaded (or not threaded)
2. Hit `<enter>` to open thread
3. Immediately press `j`/`k`

Expected
---
4. Focus is on the posts in the thead/side panel

Observed
---
4. Focus is on the timeline, it might switch to be on the posts in the thead/side panel after it finishes loading

**Comment by cheeaun** [comment]
Is this on Safari?

**Comment by hboon** [comment]
Yes

**Comment by hboon** [comment]
Try scroll the timeline so that there isn't a boosts carousell on the screen. It looks like this, observe the blue-ish selection on the timeline moves while the right pane is visible

https://user-images.githubusercontent.com/56189/222398572-b085d9aa-439a-46d9-b572-6ff4eaf4bd58.mov

**Comment by cheeaun** [comment]
Hmm still kinda hard to reproduce on my side. I can kinda reproduce it if I spam-press (is this even a valid word?) the `j` key  repetitively *while* pressing `enter` to open a post, but the focus immediately shifts to the ones in the side pane instead of still stuck in the timeline in the background. 🤔

I'm using Safari Version 16.3 (18614.4.6.1.6). Yours? Also, any extensions? 😉

**Comment by hboon** [comment]
I'm on Version 16.3 (18614.4.6.1.5)

Oh I was silly or you changed something, here's how I can reproduce it slowly now:

1. Navigate with j/k on timeline to a post that is threaded (or not threaded)
2. Hit <enter> to open thread
3. Immediately press `k` (not `j`)

I can reproduce this on both sites. Does it exhibit the same behavior?

**Comment by cheeaun** [comment]
@hboon oh wow, got it, able to reproduce now 😂

**Comment by hboon** [comment]
Heh. Updated the title to reflect the real issue :)

**Comment by hboon** [comment]
@cheeaun looks like this is fixed on dev.phanpy.social
