### ISSUE TITLE
Support exclusive lists with GotoSocial 0.17

### ISSUE THREAD

**Issue by VyrCossont** [cheeaun/phanpy#808]
**Is your feature request related to a problem? Please describe.**

GotoSocial's upcoming 0.17 release will include Mastodon-API-compatible exclusive lists. Phanpy already supports them on Mastodon instances through the "Hide posts on this list from Home/Following" list edit checkbox, and they work great.

**Describe the solution you'd like**

I'd love to see Phanpy add support for them with GtS 0.17 as well. API should be the same:
- superseriousbusiness/gotosocial#3280

Feditext and Fedicat didn't hit any issues adding it, afaik.

**Comment by graue** [comment]
Looking into this. Have a question: how can I tell the server is a GoToSocial server?

According to [GoToSocial's API docs](https://docs.gotosocial.org/en/latest/api/swagger/), `GET /api/v2/instance` returns a version string such as:

    "0.1.1 cb85f65"

If this is still the case for newer versions, it's not clear to me how a client can tell that it's dealing with version 0.17 _of GTS_ as opposed to version 0.17 of Mastodon or something else. There's no other field that says the type of server software. By contrast, my account on pixelfed.social returns a version string of:

    "3.5.3 (compatible; Pixelfed 0.12.3)"

...which allows Phanpy to determine that it's Pixelfed and, in principle (although Phanpy doesn't currently do this), to know that a feature is available in version 0.12 of Pixelfed but not version 0.11 of Pixelfed, etc.

**Comment by VyrCossont** [comment]
@graue The Mastodon API isn't the correct way to determine a server's actual version. It doesn't even usually give you the correct Mastodon API version the server's trying to fake; iirc Pixelfed has some APIs that weren't in Mastodon 3.5 and is missing a bunch that were, and I'm not counting Pixelfed-specific extensions. (Pleroma/Akkoma have similar issues.) While there is a GtS option that will return a similar fake Mastodon version string, it's not on by default, because it's intended only for use with really broken clients.

I think the correct answer is to use [NodeInfo](https://github.com/jhass/nodeinfo). Every Fedi server and many non-Fedi servers support it, and it'll have name and version fields that give you the server's actual software, not the Mastodon version it might be pretending to be. Once you've got that info, you can then attempt an `/api/v2/instance` or `/api/v1/instance` call and see if the thing actually has a Mastodon-compatible API.

This is the approach Feditext uses: real version from NodeInfo, further details from instance API.

Side note: Pleroma/Akkoma have additional details in `metadata` in their NodeInfo docs on how the server is configured and what features are available, but I think some of it is duplicated in the instance API.

**Comment by graue** [comment]
That makes sense. Too bad the NodeInfo protocol and schema don't seem to be supported by Masto.js and look rather complicated. It makes this a bigger task than it appeared to be.
