### ISSUE TITLE
Hitting the d key once bookmarks / unbookmarks every post on the page

### ISSUE THREAD

**Issue by jeffsikes** [cheeaun/phanpy#825]
**Describe the bug**
- Which site: phanpy.box464.social 
- Which site version: 2024.09.12.1c0fb61
- Which instance: mastodon.social

**To Reproduce**
1. Go to any timeline of posts
2. Accidentally or puporsefully click the "d" key
3. A mass amount of post bookmarks or unbookmarks occur.

**Expected behavior**
I think the expectation should be to bookmark the focused post. If there is no focused post, no bookmark should occur, or perhaps an error message. But only one post! Not every post that is available on the page.

**Screenshots**
I don't want to replicate the problem on my main account, then I'd have to unbookmarks 30-40 posts again. What sent me here tho was the unbookmarking part - it unbookmarked my first page of bookmarked posts when viewing the bookmarks timeline. 😭 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge
 - Version: latest, 129.0.2792.52

**Additional context**
N/A

**Comment by Steffo99** [comment]
Had the same thing happen with boosts...

Not fun. :laughing: 

@cheeaun this might be a high priority bug!

**Comment by cheeaun** [comment]
Sort of dup of https://github.com/cheeaun/phanpy/issues/795

Should be fixed here https://github.com/cheeaun/phanpy/commit/b1d75926738db1681fba58e19339c9e87ac49564

**Comment by jeffsikes** [comment]
Yes, confirmed resolved with the latest updates. Now it requires opening up the detail for a post and hitting the "d" key with that post focused. Thanks!
