### ISSUE TITLE
Don't offer translations for known languages

### ISSUE THREAD

**Issue by Alex0007** [cheeaun/phanpy#85]
User can set several "known languages" and then UI stop showing translate button for those messages. Also when translating message – transcription comes first which is not what i was looking for. I guess transcription should be hidden or at least less visible. It can take all screen space in case of big messages. 

**Describe the bug**
- Which site: dev.phanpy.social

**Expected behavior**
I don't want to see translate functionality for languages i know. After pressing "translate" button, I want to see translation, not transcription

**Screenshots**
<details>
  <summary>View</summary>
  
  Transcription goes first and takes a lot of space. And I don't want translate for Russian language at all, as I'm a native speaker
  
<img width="627" alt="Screenshot 2023-03-18 at 02 08 13" src="https://user-images.githubusercontent.com/1143226/226061550-321c5f96-e21a-4135-9329-52bfbbeba533.png">
  
</details>

**Additional context**
[Here](https://github.com/elk-zone/elk/issues/1247) is related discussion in Elk UI

**Comment by cheeaun** [comment]
Currently implemented on [production](https://phanpy.social). Feel free to open another issue if it doesn't work 🙇‍♂️
