### ISSUE TITLE
Scroll position in boosts carousel doesn't persist in Safari

### ISSUE THREAD

**Issue by zorae** [cheeaun/phanpy#87]
**Describe the bug**
The scroll position inside a boosts carousel resets on click
- Which site: both dev.phanpy.social and phanpy.social

**To Reproduce**
1. In Phanpy, navigate to a boosts carousel
2. Scroll right inside the carousel
3. Click on one of the posts in the carousel
4. The carousel's scroll position resets to its initial left position. The post I clicked on doesn't open.

**Expected behavior**
The scroll position persists and the selected post is opened

**Desktop (please complete the following information):**
 - OS: macOS 13.3
 - Browser: Safari 16.4

**Additional context**
This bug has been around for at least a few versions of Phanpy. It only happens in Safari on macOS. Neither Chrome on macOS nor Safari on iOS exhibit this behaviour.

**Comment by cheeaun** [comment]
Regarding "The post I clicked on doesn't open.", what do you see instead? It would be useful if you could attach a screen recording 🙏

Just to set expectations, I'm not on macOS 13.3 and it seems to be still in beta, so I won't be able to fix this in a timely manner 🙇 I also can't reproduce this on Safari 16.3 (18614.4.6.1.6), macOS 13.2.1 on my machine.

**Comment by zorae** [comment]
https://user-images.githubusercontent.com/6568478/226163562-3cad3257-e03f-4034-a611-db832e29877c.mov

**Comment by cheeaun** [comment]
@zorae is this still happening for you?

I just upgraded to Ventura 13.3 using Safari 16.4 (18615.1.26.11.22), unable to reproduce 🙏

**Comment by zorae** [comment]
Seems to be resolved as of 13.4 Beta (22F5037d) and Phanpy 2dde64e
