### ISSUE TITLE
Title "Post" not translated in several languages

### ISSUE THREAD

**Issue by dtalens** [cheeaun/phanpy#874]
### Site

phanpy.dtalens.com

### Version

2024.10.13.f85cf225

### Instance

mastodon.dtalens.com

### Browser

- Firefox 131.0.2 (64 bits) in Ubuntu 24.04
- Chrome 129.0.6668.100  in Ubuntu 24.04

### Bug description

String: #: src/pages/status.jsx:567

The title "Post" is not translated into Catalan and other languages, "Post" always appears when the translated word should appear. Also, the last translation of this string doesn't update correctly because "Publica" keeps appearing when "Publicació" should appear.

![image](https://github.com/user-attachments/assets/09a791e2-1eba-473d-8649-28371ad25804)

**Comment by SadmL** [comment]
Just noticed, in Russian too, I guess it is not language specific problem

**Comment by SadmL** [comment]
Updated to 71a694b74e6f1e89c295904311ca1e9e14bd7eb5, I think that this string need to be separate one, because in Russian "Post" have several means - "post" and for that case "publish". And Post header is means "Publish" now.

**Comment by cheeaun** [comment]
@SadmL sorry, this has to be separate from which "Post"? https://github.com/cheeaun/phanpy/commit/71a694b74e6f1e89c295904311ca1e9e14bd7eb5 refers to "Post" heading which should be same as the "Post" title. The other "Post" is in the composer which has a different ID and context of "Submit button in composer".

**Comment by SadmL** [comment]
@cheeaun 
Yeah, I understand. Hm... Me need to check Crowdin in that case.

**Comment by SadmL** [comment]
@cheeaun 
Checked. I mean that existent "Post" (`src/components/compose.jsx:1498`) which means "Submit button in composer" needed to be separated from Title "Post" which was presented on original message.

`src/components/compose.jsx:1498` - now translated as "publish" in Russian, which now is appeared as Title of "Post" instead actual needed "Post" translation.
![изображение](https://github.com/user-attachments/assets/d6b7c9b4-20cf-4f72-ae52-76b26f5bc78b)

**Comment by SadmL** [comment]
@cheeaun
I've added translation on Crowdin for new "Post" string

**Comment by SadmL** [comment]
@cheeaun 
Can you do same for "Following"?
![изображение](https://github.com/user-attachments/assets/9638217b-add9-4192-8b08-c8f566aedd98)

**Comment by cheeaun** [comment]
@SadmL question, how about the "Following" timeline? (it's same as "Home" timeline but not called "Home" when it's in multi-column mode). Would it be the same as (people) or (action) context? Or another different context?

![Screenshot 2024-10-14 at 8 10 36 PM](https://github.com/user-attachments/assets/6ae848b9-7313-46a0-b7d0-f7a52ae496ee)

**Comment by SadmL** [comment]
@cheeaun 
I think I can translate it as "people" context

**Comment by SadmL** [comment]
@cheeaun 
I've translated all new stuff. And I hope I've do this right.

**Comment by SadmL** [comment]
@cheeaun 
All good 👍

**Comment by dtalens** [comment]
It's solved, thanks @cheeaun
