### ISSUE TITLE
Can't select users to mention from the context menu

### ISSUE THREAD

**Issue by LukaszH77** [cheeaun/phanpy#88]
**Describe the bug**

Selecting users from context menu doesn't work.

- Which site: dev.phanpy.social

**To Reproduce**

1. Go to dev.phanpy.social
2. Start writing a new post
3. Type any mastodon user handle
4. Context menu appears with users matching
5. Can't select a user from the list neither by clicking nor pressing enter.
7. Can't navigate through the list of suggested users using the up and down arrows

**Expected behavior**
Clicking or pressing enter on the selected user should complete their handle and close the context menu.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 111

**Smartphone (please complete the following information):**
 - Device: Motorola Moto g7
 - OS: LineageOS 20
 - Browser: Chrome
 - Version: 111
 
![Zrzut ekranu z 2023-03-22 08-28-47](https://user-images.githubusercontent.com/121253127/226835578-671ffb69-e30d-4c39-b304-ff845f6acaf7.png)

**Comment by cheeaun** [comment]
Possibly fixed by https://github.com/cheeaun/phanpy/commit/668acdcf0b23a9aaecb358e57b8023108093c4d6

@LukaszH77 can you try it out on your side? (maybe need to refresh) Thanks! 🙏

**Comment by LukaszH77** [comment]
It works now! Thank you!
