### ISSUE TITLE
building from production branch fails

### ISSUE THREAD

**Issue by roughnecks** [cheeaun/phanpy#886]
### Version

2024.10.15.e3df9ff

### Instance

https://fedi.woodpeckersnest.space/

### Browser

Chrome on Windows 10 Versione 129.0.6668.101 (Build ufficiale) (a 64 bit)

### Bug description

Phanpy doesn't build

```
x Build failed in 3.18s
error during build:
[vite-plugin-pwa:build] The service was stopped: write EPIPE
file: /home/user/phanpy/src/components/compose.jsx
    at /home/user/phanpy/node_modules/esbuild/lib/main.js:737:38
    at responseCallbacks.<computed> (/home/user/phanpy/node_modules/esbuild/lib/main.js:622:9)
    at afterClose (/home/user/phanpy/node_modules/esbuild/lib/main.js:613:28)
    at /home/user/phanpy/node_modules/esbuild/lib/main.js:1983:18
    at onwriteError (node:internal/streams/writable:418:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

### To reproduce

1. git checkout production
2. npm install
3. nmp run build

**Comment by cheeaun** [comment]
Does it work if retry (multiple times)?

Did a little web search, seems like an issue with something else that's much higher level (OS-level?). This specific StackOverflow mentions disabling antivirus which may or may not fix your problem https://stackoverflow.com/a/74531253/20838
