### ISSUE TITLE
Filters are not taken into account

### ISSUE THREAD

**Issue by bmonjoie** [cheeaun/phanpy#90]
**Describe the bug**
Toots matching some filters are not filtered out of the timeline.
- Which site: phanpy.social

**To Reproduce**
1. Go to your instance's preferences screen
2. Click on 'Filters' in the menu
3. Add a new filter
4. Go to Phanpy's timeline
5. See toots that should have been filtered out.

**Expected behavior**
Toots matching one or more of the filters should be hidden from the timeline.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Browser Firefox
 - Version 111.0.1 (64-bit)

**Smartphone (please complete the following information):**
 - Device: Pixel 6Pro
 - OS: Android 13
 - Browser Firefox
 - Version 111.1.1

**Comment by cheeaun** [comment]
Currently a partial implementation on [production](https://phanpy.social).

**Comment by eliocamp** [comment]
Right now filtered posts appear as horizontal lines on desktop (they go away if the screen is narrow enough). 

![image](https://github.com/cheeaun/phanpy/assets/8617595/ceb70736-31c2-462a-bfe0-2438a0a54397)


(BTW: Censor mode is a great idea for reporting bugs!)

**Comment by cheeaun** [comment]
@eliocamp is this on Firefox?

**Comment by eliocamp** [comment]
Yes. And chrome:

![image](https://github.com/cheeaun/phanpy/assets/8617595/e6f04fc2-9d08-40b6-b703-5e370c0b58ab)

**Comment by cheeaun** [comment]
@eliocamp may I know the browser versions? Thanks

**Comment by cheeaun** [comment]
Should be fixed on prod now 🙇‍♂️
