### ISSUE TITLE
Support multiple accounts on the same server

### ISSUE THREAD

**Issue by schwindp** [cheeaun/phanpy#949]
### Site

phanpy.social

### Version

2024.11.15.12bd3b3

### Instance

chaos.social

### Browser

Firefox 132.0.2 on Windows 10

### Bug description

At this moment, Phanpy doesn't support multiple accounts that live on the same server - it uses the same (existing) browser session to log on.

### To reproduce

1. Click on the existing account's profile image
2. Open "Accounts..."
3. In the accounts dialogue, chose "Add an existing account"
4. I'm presented with the instance Log in window
5. Filling the form with the account-to-be-added's server name

As a result, I'm presented with Mastodon's account access authorization dialogue, mentioning the already-in-use account. Which is unfortunate.

### Expected behavior

Being asked for login credentials for the new account, therefor being able to set up a 2nd account on the same server to use in parallel.

**Comment by cheeaun** [comment]
@schwindp on the auth page (of your server), you can log out by clicking on the icon at the top right, to log in to another account on the same server.

**Comment by schwindp** [comment]
@cheeaun thank you, exactly that was the case. Working now as expected.
